ALTER TABLE SYNONYM DROP CONSTRAINT FK_A_SYNONYM_MEANING_MEANING;

ALTER TABLE MEANING
RENAME COLUMN MEA_ID TO DIC_ENT_ID;

ALTER TABLE MEANING
RENAME TO DICTIONARY_ENTITY;

DROP SEQUENCE IF EXISTS SEQ_MEANING;
CREATE SEQUENCE SEQ_DICTIONARY_ENTITY
	start with 2000 cache 20;

ALTER TABLE SYNONYM
RENAME COLUMN MEA_ID TO DIC_ENT_ID;

alter table SYNONYM
	add constraint FK_A_SYNONYM_DICTIONARY_ENTITY_DICTIONARY_ENTITY foreign key (DIC_ENT_ID)
	references DICTIONARY_ENTITY (DIC_ENT_ID);

create index A_SYNONYM_DICTIONARY_ENTITY_DICTIONARY_ENTITY on SYNONYM (DIC_ENT_ID asc);