package io.vertigo.chatbot.designer.domain.analytics;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datastore.impl.entitystore.EnumStoreVAccessor;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class ConversationCriteria implements DtObject {
	private static final long serialVersionUID = 1L;

	private String modelName;

	@io.vertigo.datamodel.structure.stereotype.Association(
			name = "AConversationCriteriaRatingOptions",
			fkFieldName = "rating",
			primaryDtDefinitionName = "DtRatingOption",
			primaryIsNavigable = true,
			primaryRole = "RatingOption",
			primaryLabel = "Rating",
			primaryMultiplicity = "0..1",
			foreignDtDefinitionName = "DtConversationCriteria",
			foreignIsNavigable = false,
			foreignRole = "ConversationCriteria",
			foreignLabel = "ConversationCriteria",
			foreignMultiplicity = "0..*")
	private final EnumStoreVAccessor<io.vertigo.chatbot.designer.domain.analytics.RatingOption, io.vertigo.chatbot.designer.domain.analytics.RatingOptionEnum> ratingAccessor = new EnumStoreVAccessor<>(io.vertigo.chatbot.designer.domain.analytics.RatingOption.class, "RatingOption", io.vertigo.chatbot.designer.domain.analytics.RatingOptionEnum.class);
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Model Name'.
	 * @return String modelName
	 */
	@Field(smartType = "STyLabel", label = "Model Name")
	public String getModelName() {
		return modelName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Model Name'.
	 * @param modelName String
	 */
	public void setModelName(final String modelName) {
		this.modelName = modelName;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Rating'.
	 * @return Long rating
	 */
	@io.vertigo.datamodel.structure.stereotype.ForeignKey(smartType = "STyNumber", label = "Rating", fkDefinition = "DtRatingOption" )
	public Long getRating() {
		return (Long) ratingAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Rating'.
	 * @param rating Long
	 */
	public void setRating(final Long rating) {
		ratingAccessor.setId(rating);
	}

 	/**
	 * Association : Rating.
	 * @return l'accesseur vers la propriété 'Rating'
	 */
	public EnumStoreVAccessor<io.vertigo.chatbot.designer.domain.analytics.RatingOption, io.vertigo.chatbot.designer.domain.analytics.RatingOptionEnum> ratingOption() {
		return ratingAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
