package io.vertigo.chatbot.designer.domain.analytics;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class QuestionAnswerStat implements DataObject {
	private static final long serialVersionUID = 1L;

	private Long qaId;
	private String question;
	private String catLabel;
	private Long count;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Q&A Id'.
	 * @return Long qaId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Q&A Id")
	public Long getQaId() {
		return qaId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Q&A Id'.
	 * @param qaId Long <b>Obligatoire</b>
	 */
	public void setQaId(final Long qaId) {
		this.qaId = qaId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Question'.
	 * @return String question <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Question")
	public String getQuestion() {
		return question;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Question'.
	 * @param question String <b>Obligatoire</b>
	 */
	public void setQuestion(final String question) {
		this.question = question;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Category'.
	 * @return String catLabel <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Category")
	public String getCatLabel() {
		return catLabel;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Category'.
	 * @param catLabel String <b>Obligatoire</b>
	 */
	public void setCatLabel(final String catLabel) {
		this.catLabel = catLabel;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Usage Count'.
	 * @return Long count <b>Obligatoire</b>
	 */
	@Field(smartType = "STyNumber", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Usage Count")
	public Long getCount() {
		return count;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Usage Count'.
	 * @param count Long <b>Obligatoire</b>
	 */
	public void setCount(final Long count) {
		this.count = count;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
