package io.vertigo.chatbot.designer.domain.analytics;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtStaticMasterData;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class RatingOption implements DtStaticMasterData {
	private static final long serialVersionUID = 1L;

	private Long raOptCd;
	private String label;
	private String labelFr;

	/** {@inheritDoc} */
	@Override
	public UID<RatingOption> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Code'.
	 * @return Long raOptCd <b>Obligatoire</b>
	 */
	@Field(smartType = "STyNumber", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Code")
	@io.vertigo.datamodel.structure.stereotype.SortField
	public Long getRaOptCd() {
		return raOptCd;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Code'.
	 * @param raOptCd Long <b>Obligatoire</b>
	 */
	public void setRaOptCd(final Long raOptCd) {
		this.raOptCd = raOptCd;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Title'.
	 * @return String label <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Title")
	@io.vertigo.datamodel.structure.stereotype.DisplayField
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Title'.
	 * @param label String <b>Obligatoire</b>
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Titre'.
	 * @return String labelFr <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Titre")
	public String getLabelFr() {
		return labelFr;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Titre'.
	 * @param labelFr String <b>Obligatoire</b>
	 */
	public void setLabelFr(final String labelFr) {
		this.labelFr = labelFr;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
