package io.vertigo.chatbot.designer.domain.analytics;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class RatingDetail implements DtObject {
	private static final long serialVersionUID = 1L;

	private String sessionId;
	private java.time.Instant date;
	private Long rating;
	private String comment;
	private String lastTopic;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Session ID'.
	 * @return String sessionId
	 */
	@Field(smartType = "STyIdStr", label = "Session ID")
	public String getSessionId() {
		return sessionId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Session ID'.
	 * @param sessionId String
	 */
	public void setSessionId(final String sessionId) {
		this.sessionId = sessionId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Date'.
	 * @return Instant date
	 */
	@Field(smartType = "STyInstant", label = "Date")
	public java.time.Instant getDate() {
		return date;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Date'.
	 * @param date Instant
	 */
	public void setDate(final java.time.Instant date) {
		this.date = date;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Rating'.
	 * @return Long rating
	 */
	@Field(smartType = "STyNumber", label = "Rating")
	public Long getRating() {
		return rating;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Rating'.
	 * @param rating Long
	 */
	public void setRating(final Long rating) {
		this.rating = rating;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Comment'.
	 * @return String comment
	 */
	@Field(smartType = "STyLabel", label = "Comment")
	public String getComment() {
		return comment;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Comment'.
	 * @param comment String
	 */
	public void setComment(final String comment) {
		this.comment = comment;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Last topic'.
	 * @return String lastTopic
	 */
	@Field(smartType = "STyLabel", label = "Last topic")
	public String getLastTopic() {
		return lastTopic;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Last topic'.
	 * @param lastTopic String
	 */
	public void setLastTopic(final String lastTopic) {
		this.lastTopic = lastTopic;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
