package io.vertigo.chatbot.designer.domain.analytics;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class SessionExport implements DataObject {
	private static final long serialVersionUID = 1L;

	private java.time.Instant date;
	private Long conversationCount;
	private Long userActionsCount;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Date'.
	 * @return Instant date
	 */
	@Field(smartType = "STyInstant", label = "Date")
	public java.time.Instant getDate() {
		return date;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Date'.
	 * @param date Instant
	 */
	public void setDate(final java.time.Instant date) {
		this.date = date;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Conversation count'.
	 * @return Long conversationCount
	 */
	@Field(smartType = "STyNumber", label = "Conversation count")
	public Long getConversationCount() {
		return conversationCount;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Conversation count'.
	 * @param conversationCount Long
	 */
	public void setConversationCount(final Long conversationCount) {
		this.conversationCount = conversationCount;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'User actions count'.
	 * @return Long userActionsCount
	 */
	@Field(smartType = "STyNumber", label = "User actions count")
	public Long getUserActionsCount() {
		return userActionsCount;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'User actions count'.
	 * @param userActionsCount Long
	 */
	public void setUserActionsCount(final Long userActionsCount) {
		this.userActionsCount = userActionsCount;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
