package io.vertigo.chatbot.commons.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class BotExport implements DtObject {
	private static final long serialVersionUID = 1L;

	private io.vertigo.chatbot.commons.domain.Chatbot bot;
	private String welcomeBT;
	private String endBT;
	private String fallbackBT;
	private io.vertigo.datamodel.structure.model.DtList<io.vertigo.chatbot.commons.domain.TopicExport> topics =  new io.vertigo.datamodel.structure.model.DtList<>(io.vertigo.chatbot.commons.domain.TopicExport.class);
	private String mapContext;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'chatbot'.
	 * @return Chatbot bot <b>Obligatoire</b>
	 */
	@Field(smartType = "STyDtChatbot", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "chatbot")
	public io.vertigo.chatbot.commons.domain.Chatbot getBot() {
		return bot;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'chatbot'.
	 * @param bot Chatbot <b>Obligatoire</b>
	 */
	public void setBot(final io.vertigo.chatbot.commons.domain.Chatbot bot) {
		this.bot = bot;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'welcome BT'.
	 * @return String welcomeBT <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "welcome BT")
	public String getWelcomeBT() {
		return welcomeBT;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'welcome BT'.
	 * @param welcomeBT String <b>Obligatoire</b>
	 */
	public void setWelcomeBT(final String welcomeBT) {
		this.welcomeBT = welcomeBT;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'end BT'.
	 * @return String endBT <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "end BT")
	public String getEndBT() {
		return endBT;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'end BT'.
	 * @param endBT String <b>Obligatoire</b>
	 */
	public void setEndBT(final String endBT) {
		this.endBT = endBT;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'fallback BT'.
	 * @return String fallbackBT <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "fallback BT")
	public String getFallbackBT() {
		return fallbackBT;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'fallback BT'.
	 * @param fallbackBT String <b>Obligatoire</b>
	 */
	public void setFallbackBT(final String fallbackBT) {
		this.fallbackBT = fallbackBT;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'topics export'.
	 * @return DtList de TopicExport topics
	 */
	@Field(smartType = "STyDtTopicExport", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "topics export")
	public io.vertigo.datamodel.structure.model.DtList<io.vertigo.chatbot.commons.domain.TopicExport> getTopics() {
		return topics;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'topics export'.
	 * @param topics DtList de TopicExport
	 */
	public void setTopics(final io.vertigo.datamodel.structure.model.DtList<io.vertigo.chatbot.commons.domain.TopicExport> topics) {
		io.vertigo.core.lang.Assertion.check().isNotNull(topics);
		//---
		this.topics = topics;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'map Context'.
	 * @return String mapContext <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "map Context")
	public String getMapContext() {
		return mapContext;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'map Context'.
	 * @param mapContext String <b>Obligatoire</b>
	 */
	public void setMapContext(final String mapContext) {
		this.mapContext = mapContext;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
