package io.vertigo.chatbot.commons.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtStaticMasterData;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class ChatbotFormat implements DtStaticMasterData {
	private static final long serialVersionUID = 1L;

	private String cftCd;
	private String label;
	private String labelFr;
	private Long sortOrder;

	/** {@inheritDoc} */
	@Override
	public UID<ChatbotFormat> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'ID'.
	 * @return String cftCd <b>Obligatoire</b>
	 */
	@Field(smartType = "STyCode", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "ID")
	public String getCftCd() {
		return cftCd;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'ID'.
	 * @param cftCd String <b>Obligatoire</b>
	 */
	public void setCftCd(final String cftCd) {
		this.cftCd = cftCd;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Title'.
	 * @return String label <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Title")
	@io.vertigo.datamodel.structure.stereotype.DisplayField
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Title'.
	 * @param label String <b>Obligatoire</b>
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'TitleFr'.
	 * @return String labelFr <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "TitleFr")
	public String getLabelFr() {
		return labelFr;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'TitleFr'.
	 * @param labelFr String <b>Obligatoire</b>
	 */
	public void setLabelFr(final String labelFr) {
		this.labelFr = labelFr;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Order'.
	 * @return Long sortOrder <b>Obligatoire</b>
	 */
	@Field(smartType = "STyNumber", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Order")
	@io.vertigo.datamodel.structure.stereotype.SortField
	public Long getSortOrder() {
		return sortOrder;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Order'.
	 * @param sortOrder Long <b>Obligatoire</b>
	 */
	public void setSortOrder(final Long sortOrder) {
		this.sortOrder = sortOrder;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
