package io.vertigo.chatbot.commons.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.Entity;
import io.vertigo.datamodel.data.model.UID;
import io.vertigo.datastore.impl.entitystore.StoreVAccessor;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class ConfluenceSettingSpace implements Entity {
	private static final long serialVersionUID = 1L;

	private Long conSetSpaceId;
	private String space;

	@io.vertigo.datamodel.data.stereotype.Association(
			name = "AConfluenceSettingSpace",
			fkFieldName = "confluencesettingId",
			primaryDtDefinitionName = "DtConfluenceSetting",
			primaryIsNavigable = true,
			primaryRole = "ConfluenceSetting",
			primaryLabel = "ConfluenceSetting",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtConfluenceSettingSpace",
			foreignIsNavigable = false,
			foreignRole = "ConfluenceSettingSpace",
			foreignLabel = "ConfluenceSettingSpace",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.chatbot.commons.domain.ConfluenceSetting> confluencesettingIdAccessor = new StoreVAccessor<>(io.vertigo.chatbot.commons.domain.ConfluenceSetting.class, "ConfluenceSetting");

	/** {@inheritDoc} */
	@Override
	public UID<ConfluenceSettingSpace> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Confluence setting space id'.
	 * @return Long conSetSpaceId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Confluence setting space id")
	public Long getConSetSpaceId() {
		return conSetSpaceId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Confluence setting space id'.
	 * @param conSetSpaceId Long <b>Obligatoire</b>
	 */
	public void setConSetSpaceId(final Long conSetSpaceId) {
		this.conSetSpaceId = conSetSpaceId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Space'.
	 * @return String space <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Space")
	public String getSpace() {
		return space;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Space'.
	 * @param space String <b>Obligatoire</b>
	 */
	public void setSpace(final String space) {
		this.space = space;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'ConfluenceSetting'.
	 * @return Long confluencesettingId <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.data.stereotype.ForeignKey(smartType = "STyId", label = "ConfluenceSetting", fkDefinition = "DtConfluenceSetting", cardinality = io.vertigo.core.lang.Cardinality.ONE )
	public Long getConfluencesettingId() {
		return (Long) confluencesettingIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'ConfluenceSetting'.
	 * @param confluencesettingId Long <b>Obligatoire</b>
	 */
	public void setConfluencesettingId(final Long confluencesettingId) {
		confluencesettingIdAccessor.setId(confluencesettingId);
	}

 	/**
	 * Association : ConfluenceSetting.
	 * @return l'accesseur vers la propriété 'ConfluenceSetting'
	 */
	public StoreVAccessor<io.vertigo.chatbot.commons.domain.ConfluenceSetting> confluenceSetting() {
		return confluencesettingIdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
