package io.vertigo.chatbot.commons.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datastore.impl.entitystore.EnumStoreVAccessor;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class ContextValueExport implements DataObject {
	private static final long serialVersionUID = 1L;

	private String label;
	private String value;

	@io.vertigo.datamodel.data.stereotype.Association(
			name = "AContextValueExportTypeOperator",
			fkFieldName = "tyopCd",
			primaryDtDefinitionName = "DtTypeOperator",
			primaryIsNavigable = true,
			primaryRole = "TypeOperator",
			primaryLabel = "Value operator",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtContextValueExport",
			foreignIsNavigable = false,
			foreignRole = "ContextValueExport",
			foreignLabel = "ContextValueExport",
			foreignMultiplicity = "0..*")
	private final EnumStoreVAccessor<io.vertigo.chatbot.commons.domain.TypeOperator, io.vertigo.chatbot.commons.domain.TypeOperatorEnum> tyopCdAccessor = new EnumStoreVAccessor<>(io.vertigo.chatbot.commons.domain.TypeOperator.class, "TypeOperator", io.vertigo.chatbot.commons.domain.TypeOperatorEnum.class);
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Context label'.
	 * @return String label <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Context label")
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Context label'.
	 * @param label String <b>Obligatoire</b>
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Context value'.
	 * @return String value <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Context value")
	public String getValue() {
		return value;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Context value'.
	 * @param value String <b>Obligatoire</b>
	 */
	public void setValue(final String value) {
		this.value = value;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Value operator'.
	 * @return String tyopCd <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.data.stereotype.ForeignKey(smartType = "STyCode", label = "Value operator", fkDefinition = "DtTypeOperator", cardinality = io.vertigo.core.lang.Cardinality.ONE )
	public String getTyopCd() {
		return (String) tyopCdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Value operator'.
	 * @param tyopCd String <b>Obligatoire</b>
	 */
	public void setTyopCd(final String tyopCd) {
		tyopCdAccessor.setId(tyopCd);
	}

 	/**
	 * Association : Value operator.
	 * @return l'accesseur vers la propriété 'Value operator'
	 */
	public EnumStoreVAccessor<io.vertigo.chatbot.commons.domain.TypeOperator, io.vertigo.chatbot.commons.domain.TypeOperatorEnum> typeOperator() {
		return tyopCdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
