package io.vertigo.chatbot.commons.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.Entity;
import io.vertigo.datastore.impl.entitystore.EnumStoreVAccessor;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datastore.impl.entitystore.StoreVAccessor;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class JiraFieldSetting implements Entity {
	private static final long serialVersionUID = 1L;

	private Long jirFieldSetId;
	private Boolean enabled;
	private Boolean mandatory;

	@io.vertigo.datamodel.structure.stereotype.Association(
			name = "AJiraFieldSettingChatbot",
			fkFieldName = "botId",
			primaryDtDefinitionName = "DtChatbot",
			primaryIsNavigable = true,
			primaryRole = "Chatbot",
			primaryLabel = "Chatbot",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtJiraFieldSetting",
			foreignIsNavigable = false,
			foreignRole = "JiraFieldSetting",
			foreignLabel = "JiraFieldSetting",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.chatbot.commons.domain.Chatbot> botIdAccessor = new StoreVAccessor<>(io.vertigo.chatbot.commons.domain.Chatbot.class, "Chatbot");

	@io.vertigo.datamodel.structure.stereotype.Association(
			name = "AJiraFieldSettingJiraField",
			fkFieldName = "jirFieldCd",
			primaryDtDefinitionName = "DtJiraField",
			primaryIsNavigable = true,
			primaryRole = "JiraField",
			primaryLabel = "Field",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtJiraFieldSetting",
			foreignIsNavigable = false,
			foreignRole = "JiraFieldSetting",
			foreignLabel = "JiraFieldSetting",
			foreignMultiplicity = "0..*")
	private final EnumStoreVAccessor<io.vertigo.chatbot.commons.domain.JiraField, io.vertigo.chatbot.commons.domain.JiraFieldEnum> jirFieldCdAccessor = new EnumStoreVAccessor<>(io.vertigo.chatbot.commons.domain.JiraField.class, "JiraField", io.vertigo.chatbot.commons.domain.JiraFieldEnum.class);

	/** {@inheritDoc} */
	@Override
	public UID<JiraFieldSetting> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Jira field setting id'.
	 * @return Long jirFieldSetId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Jira field setting id")
	public Long getJirFieldSetId() {
		return jirFieldSetId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Jira field setting id'.
	 * @param jirFieldSetId Long <b>Obligatoire</b>
	 */
	public void setJirFieldSetId(final Long jirFieldSetId) {
		this.jirFieldSetId = jirFieldSetId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Jira field enabled'.
	 * @return Boolean enabled <b>Obligatoire</b>
	 */
	@Field(smartType = "STyYesNo", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Jira field enabled")
	public Boolean getEnabled() {
		return enabled;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Jira field enabled'.
	 * @param enabled Boolean <b>Obligatoire</b>
	 */
	public void setEnabled(final Boolean enabled) {
		this.enabled = enabled;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Jira field mandatory'.
	 * @return Boolean mandatory <b>Obligatoire</b>
	 */
	@Field(smartType = "STyYesNo", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Jira field mandatory")
	public Boolean getMandatory() {
		return mandatory;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Jira field mandatory'.
	 * @param mandatory Boolean <b>Obligatoire</b>
	 */
	public void setMandatory(final Boolean mandatory) {
		this.mandatory = mandatory;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Chatbot'.
	 * @return Long botId <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.structure.stereotype.ForeignKey(smartType = "STyId", label = "Chatbot", fkDefinition = "DtChatbot" )
	public Long getBotId() {
		return (Long) botIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Chatbot'.
	 * @param botId Long <b>Obligatoire</b>
	 */
	public void setBotId(final Long botId) {
		botIdAccessor.setId(botId);
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Field'.
	 * @return String jirFieldCd <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.structure.stereotype.ForeignKey(smartType = "STyCode", label = "Field", fkDefinition = "DtJiraField" )
	public String getJirFieldCd() {
		return (String) jirFieldCdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Field'.
	 * @param jirFieldCd String <b>Obligatoire</b>
	 */
	public void setJirFieldCd(final String jirFieldCd) {
		jirFieldCdAccessor.setId(jirFieldCd);
	}

 	/**
	 * Association : Chatbot.
	 * @return l'accesseur vers la propriété 'Chatbot'
	 */
	public StoreVAccessor<io.vertigo.chatbot.commons.domain.Chatbot> chatbot() {
		return botIdAccessor;
	}

 	/**
	 * Association : Field.
	 * @return l'accesseur vers la propriété 'Field'
	 */
	public EnumStoreVAccessor<io.vertigo.chatbot.commons.domain.JiraField, io.vertigo.chatbot.commons.domain.JiraFieldEnum> jiraField() {
		return jirFieldCdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
