package io.vertigo.chatbot.commons.domain;

import io.vertigo.dynamo.domain.model.Entity;
import io.vertigo.dynamo.domain.model.EnumVAccessor;
import io.vertigo.dynamo.domain.model.ListVAccessor;
import io.vertigo.dynamo.domain.model.UID;
import io.vertigo.dynamo.domain.model.VAccessor;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class Person implements Entity {
	private static final long serialVersionUID = 1L;

	private Long perId;
	private String login;
	private String name;
	private String password;
	private String passwordNew;

	@io.vertigo.dynamo.domain.stereotype.Association(
			name = "APersonGroups",
			fkFieldName = "grpId",
			primaryDtDefinitionName = "DtGroups",
			primaryIsNavigable = true,
			primaryRole = "Groups",
			primaryLabel = "Group",
			primaryMultiplicity = "0..1",
			foreignDtDefinitionName = "DtPerson",
			foreignIsNavigable = false,
			foreignRole = "Person",
			foreignLabel = "Person",
			foreignMultiplicity = "0..*")
	private final VAccessor<io.vertigo.chatbot.commons.domain.Groups> grpIdAccessor = new VAccessor<>(io.vertigo.chatbot.commons.domain.Groups.class, "Groups");

	@io.vertigo.dynamo.domain.stereotype.Association(
			name = "APersonRole",
			fkFieldName = "rolCd",
			primaryDtDefinitionName = "DtPersonRole",
			primaryIsNavigable = true,
			primaryRole = "PersonRole",
			primaryLabel = "Role",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtPerson",
			foreignIsNavigable = false,
			foreignRole = "Person",
			foreignLabel = "Person",
			foreignMultiplicity = "0..*")
	private final EnumVAccessor<io.vertigo.chatbot.commons.domain.PersonRole, io.vertigo.chatbot.commons.domain.PersonRoleEnum> rolCdAccessor = new EnumVAccessor<>(io.vertigo.chatbot.commons.domain.PersonRole.class, "PersonRole", io.vertigo.chatbot.commons.domain.PersonRoleEnum.class);

	@io.vertigo.dynamo.domain.stereotype.AssociationNN(
			name = "AnnChatbotPerson",
			tableName = "CHA_PER_RIGHTS",
			dtDefinitionA = "DtPerson",
			dtDefinitionB = "DtChatbot",
			navigabilityA = true,
			navigabilityB = true,
			roleA = "Persons",
			roleB = "Chatbots",
			labelA = "Persons",
			labelB = "Chatbots")
	private final ListVAccessor<io.vertigo.chatbot.commons.domain.Chatbot> chatbotsAccessor = new ListVAccessor<>(this, "AnnChatbotPerson", "Chatbots");

	/** {@inheritDoc} */
	@Override
	public UID<Person> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return Long perId <b>Obligatoire</b>
	 */
	@Field(domain = "DoId", type = "ID", required = true, label = "Id")
	public Long getPerId() {
		return perId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id'.
	 * @param perId Long <b>Obligatoire</b>
	 */
	public void setPerId(final Long perId) {
		this.perId = perId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Login'.
	 * @return String login <b>Obligatoire</b>
	 */
	@Field(domain = "DoLabel", required = true, label = "Login")
	public String getLogin() {
		return login;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Login'.
	 * @param login String <b>Obligatoire</b>
	 */
	public void setLogin(final String login) {
		this.login = login;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Name'.
	 * @return String name <b>Obligatoire</b>
	 */
	@Field(domain = "DoLabel", required = true, label = "Name")
	public String getName() {
		return name;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Name'.
	 * @param name String <b>Obligatoire</b>
	 */
	public void setName(final String name) {
		this.name = name;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Password'.
	 * @return String password <b>Obligatoire</b>
	 */
	@Field(domain = "DoPassword", required = true, label = "Password")
	public String getPassword() {
		return password;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Password'.
	 * @param password String <b>Obligatoire</b>
	 */
	public void setPassword(final String password) {
		this.password = password;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'New password'.
	 * @return String passwordNew
	 */
	@Field(domain = "DoPassword", persistent = false, label = "New password")
	public String getPasswordNew() {
		return passwordNew;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'New password'.
	 * @param passwordNew String
	 */
	public void setPasswordNew(final String passwordNew) {
		this.passwordNew = passwordNew;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Group'.
	 * @return Long grpId
	 */
	@Field(domain = "DoId", type = "FOREIGN_KEY", label = "Group")
	public Long getGrpId() {
		return (Long) grpIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Group'.
	 * @param grpId Long
	 */
	public void setGrpId(final Long grpId) {
		grpIdAccessor.setId(grpId);
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Role'.
	 * @return String rolCd <b>Obligatoire</b>
	 */
	@Field(domain = "DoCode", type = "FOREIGN_KEY", required = true, label = "Role")
	public String getRolCd() {
		return (String) rolCdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Role'.
	 * @param rolCd String <b>Obligatoire</b>
	 */
	public void setRolCd(final String rolCd) {
		rolCdAccessor.setId(rolCd);
	}

 	/**
	 * Association : Group.
	 * @return l'accesseur vers la propriété 'Group'
	 */
	public VAccessor<io.vertigo.chatbot.commons.domain.Groups> groups() {
		return grpIdAccessor;
	}

 	/**
	 * Association : Role.
	 * @return l'accesseur vers la propriété 'Role'
	 */
	public EnumVAccessor<io.vertigo.chatbot.commons.domain.PersonRole, io.vertigo.chatbot.commons.domain.PersonRoleEnum> personRole() {
		return rolCdAccessor;
	}

	/**
	 * Association : Chatbots.
	 * @return l'accesseur vers la propriété 'Chatbots'
	 */
	public ListVAccessor<io.vertigo.chatbot.commons.domain.Chatbot> chatbots() {
		return chatbotsAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
