package io.vertigo.chatbot.commons.domain;

import io.vertigo.dynamo.domain.model.DtStaticMasterData;
import io.vertigo.dynamo.domain.model.UID;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class PersonRole implements DtStaticMasterData {
	private static final long serialVersionUID = 1L;

	private String rolCd;
	private String label;
	private Long sortOrder;

	/** {@inheritDoc} */
	@Override
	public UID<PersonRole> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Code'.
	 * @return String rolCd <b>Obligatoire</b>
	 */
	@Field(domain = "DoCode", type = "ID", required = true, label = "Code")
	public String getRolCd() {
		return rolCd;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Code'.
	 * @param rolCd String <b>Obligatoire</b>
	 */
	public void setRolCd(final String rolCd) {
		this.rolCd = rolCd;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Label'.
	 * @return String label <b>Obligatoire</b>
	 */
	@Field(domain = "DoLabel", required = true, label = "Label")
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Label'.
	 * @param label String <b>Obligatoire</b>
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Order'.
	 * @return Long sortOrder <b>Obligatoire</b>
	 */
	@Field(domain = "DoNumber", required = true, label = "Order")
	public Long getSortOrder() {
		return sortOrder;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Order'.
	 * @param sortOrder Long <b>Obligatoire</b>
	 */
	public void setSortOrder(final Long sortOrder) {
		this.sortOrder = sortOrder;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
