package io.vertigo.chatbot.commons.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.Entity;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datastore.impl.entitystore.StoreVAccessor;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class WelcomeTourStep implements Entity {
	private static final long serialVersionUID = 1L;

	private Long welStepId;
	private String id;
	private String text;
	private String title;
	private Long sequence;
	private Boolean enabled;

	@io.vertigo.datamodel.structure.stereotype.Association(
			name = "AWelcomeTourWelcomeTourSteps",
			fkFieldName = "tourId",
			primaryDtDefinitionName = "DtWelcomeTour",
			primaryIsNavigable = true,
			primaryRole = "WelcomeTour",
			primaryLabel = "Tour",
			primaryMultiplicity = "0..1",
			foreignDtDefinitionName = "DtWelcomeTourStep",
			foreignIsNavigable = false,
			foreignRole = "WelcomeTourStep",
			foreignLabel = "WelcomeTourStep",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.chatbot.commons.domain.WelcomeTour> tourIdAccessor = new StoreVAccessor<>(io.vertigo.chatbot.commons.domain.WelcomeTour.class, "WelcomeTour");

	/** {@inheritDoc} */
	@Override
	public UID<WelcomeTourStep> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Welcome tour step id'.
	 * @return Long welStepId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Welcome tour step id")
	public Long getWelStepId() {
		return welStepId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Welcome tour step id'.
	 * @param welStepId Long <b>Obligatoire</b>
	 */
	public void setWelStepId(final Long welStepId) {
		this.welStepId = welStepId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return String id <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Id")
	public String getId() {
		return id;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Id'.
	 * @param id String <b>Obligatoire</b>
	 */
	public void setId(final String id) {
		this.id = id;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Text'.
	 * @return String text <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Text")
	public String getText() {
		return text;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Text'.
	 * @param text String <b>Obligatoire</b>
	 */
	public void setText(final String text) {
		this.text = text;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Title'.
	 * @return String title
	 */
	@Field(smartType = "STyLabel", label = "Title")
	public String getTitle() {
		return title;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Title'.
	 * @param title String
	 */
	public void setTitle(final String title) {
		this.title = title;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Sequence'.
	 * @return Long sequence
	 */
	@Field(smartType = "STyNumber", label = "Sequence")
	public Long getSequence() {
		return sequence;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Sequence'.
	 * @param sequence Long
	 */
	public void setSequence(final Long sequence) {
		this.sequence = sequence;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Enabled'.
	 * @return Boolean enabled
	 */
	@Field(smartType = "STyYesNo", label = "Enabled")
	public Boolean getEnabled() {
		return enabled;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Enabled'.
	 * @param enabled Boolean
	 */
	public void setEnabled(final Boolean enabled) {
		this.enabled = enabled;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Tour'.
	 * @return Long tourId
	 */
	@io.vertigo.datamodel.structure.stereotype.ForeignKey(smartType = "STyId", label = "Tour", fkDefinition = "DtWelcomeTour" )
	public Long getTourId() {
		return (Long) tourIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Tour'.
	 * @param tourId Long
	 */
	public void setTourId(final Long tourId) {
		tourIdAccessor.setId(tourId);
	}

 	/**
	 * Association : Tour.
	 * @return l'accesseur vers la propriété 'Tour'
	 */
	public StoreVAccessor<io.vertigo.chatbot.commons.domain.WelcomeTour> welcomeTour() {
		return tourIdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
