package io.vertigo.chatbot.designer.builder.welcomeTourStep;

import javax.inject.Inject;

import io.vertigo.core.node.Node;
import io.vertigo.core.lang.Assertion;
import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.task.TaskManager;
import io.vertigo.datamodel.task.definitions.TaskDefinition;
import io.vertigo.datamodel.task.model.Task;
import io.vertigo.datamodel.task.model.TaskBuilder;
import io.vertigo.datastore.impl.dao.StoreServices;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
 @Generated
public final class WelcomeTourStepPAO implements StoreServices {
	private final TaskManager taskManager;

	/**
	 * Constructeur.
	 * @param taskManager Manager des Task
	 */
	@Inject
	public WelcomeTourStepPAO(final TaskManager taskManager) {
		Assertion.check().isNotNull(taskManager);
		//-----
		this.taskManager = taskManager;
	}

	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Node.getNode().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TkGetNextWelcomeTourStepSequence.
	 * @param tourId Long
	 * @return Long nextWelcomeTourStepSequence
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkGetNextWelcomeTourStepSequence",
			request = """
			select coalesce(max(sequence) + 1, 1)
			from welcome_tour_step wts
			where wts.tour_id = #tourId#""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyNumber", name = "nextWelcomeTourStepSequence")
	public Long getNextWelcomeTourStepSequence(@io.vertigo.datamodel.task.proxy.TaskInput(name = "tourId", smartType = "STyId") final Long tourId) {
		final Task task = createTaskBuilder("TkGetNextWelcomeTourStepSequence")
				.addValue("tourId", tourId)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TkReorderWelcomeTourStepAfterStepDelete.
	 * @param tourId Long
	 * @param deletedSequence Long
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkReorderWelcomeTourStepAfterStepDelete",
			request = """
			update welcome_tour_step
			set sequence = (sequence - 1)
			where tour_id = #tourId# and sequence > #deletedSequence#""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineProc.class)
	public void reorderWelcomeTourStepAfterStepDelete(@io.vertigo.datamodel.task.proxy.TaskInput(name = "tourId", smartType = "STyId") final Long tourId, @io.vertigo.datamodel.task.proxy.TaskInput(name = "deletedSequence", smartType = "STyNumber") final Long deletedSequence) {
		final Task task = createTaskBuilder("TkReorderWelcomeTourStepAfterStepDelete")
				.addValue("tourId", tourId)
				.addValue("deletedSequence", deletedSequence)
				.build();
		getTaskManager().execute(task);
	}

	private TaskManager getTaskManager() {
		return taskManager;
	}
}
