package io.vertigo.chatbot.designer.domain.admin;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class SelectProfilChatbotPerson implements DataObject {
	private static final long serialVersionUID = 1L;

	private java.util.List<Long> perId = new java.util.ArrayList<>();
	private String prfId;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Person id'.
	 * @return List de Long perId
	 */
	@Field(smartType = "STyId", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Person id")
	public java.util.List<Long> getPerId() {
		return perId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Person id'.
	 * @param perId List de Long
	 */
	public void setPerId(final java.util.List<Long> perId) {
		io.vertigo.core.lang.Assertion.check().isNotNull(perId);
		//---
		this.perId = perId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Profil cd'.
	 * @return String prfId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyCode", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Profil cd")
	public String getPrfId() {
		return prfId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Profil cd'.
	 * @param prfId String <b>Obligatoire</b>
	 */
	public void setPrfId(final String prfId) {
		this.prfId = prfId;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
