package io.vertigo.chatbot.designer.domain.monitoring;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class MonitoringDetailIHM implements DataObject {
	private static final long serialVersionUID = 1L;

	private Boolean antivirusAlive;
	private Boolean globalAlertingEnabled;
	private io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.designer.domain.monitoring.MonitoringBotDetailIHM> bots =  new io.vertigo.datamodel.data.model.DtList<>(io.vertigo.chatbot.designer.domain.monitoring.MonitoringBotDetailIHM.class);
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Antivirus alive'.
	 * @return Boolean antivirusAlive <b>Obligatoire</b>
	 */
	@Field(smartType = "STyYesNo", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Antivirus alive")
	public Boolean getAntivirusAlive() {
		return antivirusAlive;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Antivirus alive'.
	 * @param antivirusAlive Boolean <b>Obligatoire</b>
	 */
	public void setAntivirusAlive(final Boolean antivirusAlive) {
		this.antivirusAlive = antivirusAlive;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Global Alerting enabled'.
	 * @return Boolean globalAlertingEnabled <b>Obligatoire</b>
	 */
	@Field(smartType = "STyYesNo", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Global Alerting enabled")
	public Boolean getGlobalAlertingEnabled() {
		return globalAlertingEnabled;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Global Alerting enabled'.
	 * @param globalAlertingEnabled Boolean <b>Obligatoire</b>
	 */
	public void setGlobalAlertingEnabled(final Boolean globalAlertingEnabled) {
		this.globalAlertingEnabled = globalAlertingEnabled;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Bot monitoring details'.
	 * @return DtList de MonitoringBotDetailIHM bots
	 */
	@Field(smartType = "STyDtMonitoringBotDetailIHM", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Bot monitoring details")
	public io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.designer.domain.monitoring.MonitoringBotDetailIHM> getBots() {
		return bots;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Bot monitoring details'.
	 * @param bots DtList de MonitoringBotDetailIHM
	 */
	public void setBots(final io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.designer.domain.monitoring.MonitoringBotDetailIHM> bots) {
		io.vertigo.core.lang.Assertion.check().isNotNull(bots);
		//---
		this.bots = bots;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
