package io.vertigo.chatbot.designer.domain.monitoring;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class MonitoringBotDetailIHM implements DataObject {
	private static final long serialVersionUID = 1L;

	private String name;
	private Long botId;
	private Boolean alertingEnabled;
	private io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.designer.domain.monitoring.MonitoringRunnerDetailIHM> runners =  new io.vertigo.datamodel.data.model.DtList<>(io.vertigo.chatbot.designer.domain.monitoring.MonitoringRunnerDetailIHM.class);
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Bot name'.
	 * @return String name <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Bot name")
	public String getName() {
		return name;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Bot name'.
	 * @param name String <b>Obligatoire</b>
	 */
	public void setName(final String name) {
		this.name = name;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Bot ID'.
	 * @return Long botId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Bot ID")
	public Long getBotId() {
		return botId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Bot ID'.
	 * @param botId Long <b>Obligatoire</b>
	 */
	public void setBotId(final Long botId) {
		this.botId = botId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Alerting enabled'.
	 * @return Boolean alertingEnabled <b>Obligatoire</b>
	 */
	@Field(smartType = "STyYesNo", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Alerting enabled")
	public Boolean getAlertingEnabled() {
		return alertingEnabled;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Alerting enabled'.
	 * @param alertingEnabled Boolean <b>Obligatoire</b>
	 */
	public void setAlertingEnabled(final Boolean alertingEnabled) {
		this.alertingEnabled = alertingEnabled;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Runners'.
	 * @return DtList de MonitoringRunnerDetailIHM runners
	 */
	@Field(smartType = "STyDtMonitoringRunnerDetailIHM", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Runners")
	public io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.designer.domain.monitoring.MonitoringRunnerDetailIHM> getRunners() {
		return runners;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Runners'.
	 * @param runners DtList de MonitoringRunnerDetailIHM
	 */
	public void setRunners(final io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.designer.domain.monitoring.MonitoringRunnerDetailIHM> runners) {
		io.vertigo.core.lang.Assertion.check().isNotNull(runners);
		//---
		this.runners = runners;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
