/**
 * vertigo - simple java starter
 *
 * Copyright (C) 2020, Vertigo.io, team@vertigo.io
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.vertigo.chatbot.executor.domain;

import io.vertigo.dynamo.domain.model.DtObject;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class RasaConfig implements DtObject {
	private static final long serialVersionUID = 1L;

	private String domain;
	private String stories;
	private String nlu;
	private String config;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'domain'.
	 * @return String domain
	 */
	@Field(domain = "DoText", label = "domain")
	public String getDomain() {
		return domain;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'domain'.
	 * @param domain String
	 */
	public void setDomain(final String domain) {
		this.domain = domain;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'stories'.
	 * @return String stories
	 */
	@Field(domain = "DoText", label = "stories")
	public String getStories() {
		return stories;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'stories'.
	 * @param stories String
	 */
	public void setStories(final String stories) {
		this.stories = stories;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'nlu'.
	 * @return String nlu
	 */
	@Field(domain = "DoText", label = "nlu")
	public String getNlu() {
		return nlu;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'nlu'.
	 * @param nlu String
	 */
	public void setNlu(final String nlu) {
		this.nlu = nlu;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'config'.
	 * @return String config
	 */
	@Field(domain = "DoText", label = "config")
	public String getConfig() {
		return config;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'config'.
	 * @param config String
	 */
	public void setConfig(final String config) {
		this.config = config;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
