package io.vertigo.chatbot.commons.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class BotExport implements DataObject {
	private static final long serialVersionUID = 1L;

	private io.vertigo.chatbot.commons.domain.Chatbot bot;
	private String welcomeBT;
	private String endBT;
	private String fallbackBT;
	private String idleBT;
	private String ratingBT;
	private io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.commons.domain.TopicExport> topics =  new io.vertigo.datamodel.data.model.DtList<>(io.vertigo.chatbot.commons.domain.TopicExport.class);
	private io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.commons.domain.WelcomeTourExport> welcomeTours =  new io.vertigo.datamodel.data.model.DtList<>(io.vertigo.chatbot.commons.domain.WelcomeTourExport.class);
	private io.vertigo.chatbot.commons.domain.ConfluenceSettingExport confluenceSetting;
	private io.vertigo.chatbot.commons.domain.JiraSettingExport jiraSetting;
	private io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.commons.domain.JiraFieldSettingExport> jiraFieldSetting =  new io.vertigo.datamodel.data.model.DtList<>(io.vertigo.chatbot.commons.domain.JiraFieldSettingExport.class);
	private String questionAnswerList;
	private String mapContext;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'chatbot'.
	 * @return Chatbot bot <b>Obligatoire</b>
	 */
	@Field(smartType = "STyDtChatbot", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "chatbot")
	public io.vertigo.chatbot.commons.domain.Chatbot getBot() {
		return bot;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'chatbot'.
	 * @param bot Chatbot <b>Obligatoire</b>
	 */
	public void setBot(final io.vertigo.chatbot.commons.domain.Chatbot bot) {
		this.bot = bot;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'welcome BT'.
	 * @return String welcomeBT <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "welcome BT")
	public String getWelcomeBT() {
		return welcomeBT;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'welcome BT'.
	 * @param welcomeBT String <b>Obligatoire</b>
	 */
	public void setWelcomeBT(final String welcomeBT) {
		this.welcomeBT = welcomeBT;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'end BT'.
	 * @return String endBT <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "end BT")
	public String getEndBT() {
		return endBT;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'end BT'.
	 * @param endBT String <b>Obligatoire</b>
	 */
	public void setEndBT(final String endBT) {
		this.endBT = endBT;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'fallback BT'.
	 * @return String fallbackBT <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "fallback BT")
	public String getFallbackBT() {
		return fallbackBT;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'fallback BT'.
	 * @param fallbackBT String <b>Obligatoire</b>
	 */
	public void setFallbackBT(final String fallbackBT) {
		this.fallbackBT = fallbackBT;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'idle BT'.
	 * @return String idleBT <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "idle BT")
	public String getIdleBT() {
		return idleBT;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'idle BT'.
	 * @param idleBT String <b>Obligatoire</b>
	 */
	public void setIdleBT(final String idleBT) {
		this.idleBT = idleBT;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'rating BT'.
	 * @return String ratingBT <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "rating BT")
	public String getRatingBT() {
		return ratingBT;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'rating BT'.
	 * @param ratingBT String <b>Obligatoire</b>
	 */
	public void setRatingBT(final String ratingBT) {
		this.ratingBT = ratingBT;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'topics export'.
	 * @return DtList de TopicExport topics
	 */
	@Field(smartType = "STyDtTopicExport", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "topics export")
	public io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.commons.domain.TopicExport> getTopics() {
		return topics;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'topics export'.
	 * @param topics DtList de TopicExport
	 */
	public void setTopics(final io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.commons.domain.TopicExport> topics) {
		io.vertigo.core.lang.Assertion.check().isNotNull(topics);
		//---
		this.topics = topics;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Welcome tours'.
	 * @return DtList de WelcomeTourExport welcomeTours
	 */
	@Field(smartType = "STyDtWelcomeTourExport", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Welcome tours")
	public io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.commons.domain.WelcomeTourExport> getWelcomeTours() {
		return welcomeTours;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Welcome tours'.
	 * @param welcomeTours DtList de WelcomeTourExport
	 */
	public void setWelcomeTours(final io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.commons.domain.WelcomeTourExport> welcomeTours) {
		io.vertigo.core.lang.Assertion.check().isNotNull(welcomeTours);
		//---
		this.welcomeTours = welcomeTours;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Confluence setting'.
	 * @return ConfluenceSettingExport confluenceSetting
	 */
	@Field(smartType = "STyDtConfluenceSettingExport", label = "Confluence setting")
	public io.vertigo.chatbot.commons.domain.ConfluenceSettingExport getConfluenceSetting() {
		return confluenceSetting;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Confluence setting'.
	 * @param confluenceSetting ConfluenceSettingExport
	 */
	public void setConfluenceSetting(final io.vertigo.chatbot.commons.domain.ConfluenceSettingExport confluenceSetting) {
		this.confluenceSetting = confluenceSetting;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Jira setting'.
	 * @return JiraSettingExport jiraSetting
	 */
	@Field(smartType = "STyDtJiraSettingExport", label = "Jira setting")
	public io.vertigo.chatbot.commons.domain.JiraSettingExport getJiraSetting() {
		return jiraSetting;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Jira setting'.
	 * @param jiraSetting JiraSettingExport
	 */
	public void setJiraSetting(final io.vertigo.chatbot.commons.domain.JiraSettingExport jiraSetting) {
		this.jiraSetting = jiraSetting;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Jira fields setting'.
	 * @return DtList de JiraFieldSettingExport jiraFieldSetting
	 */
	@Field(smartType = "STyDtJiraFieldSettingExport", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Jira fields setting")
	public io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.commons.domain.JiraFieldSettingExport> getJiraFieldSetting() {
		return jiraFieldSetting;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Jira fields setting'.
	 * @param jiraFieldSetting DtList de JiraFieldSettingExport
	 */
	public void setJiraFieldSetting(final io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.commons.domain.JiraFieldSettingExport> jiraFieldSetting) {
		io.vertigo.core.lang.Assertion.check().isNotNull(jiraFieldSetting);
		//---
		this.jiraFieldSetting = jiraFieldSetting;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Questions answers List'.
	 * @return String questionAnswerList <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Questions answers List")
	public String getQuestionAnswerList() {
		return questionAnswerList;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Questions answers List'.
	 * @param questionAnswerList String <b>Obligatoire</b>
	 */
	public void setQuestionAnswerList(final String questionAnswerList) {
		this.questionAnswerList = questionAnswerList;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'map Context'.
	 * @return String mapContext <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "map Context")
	public String getMapContext() {
		return mapContext;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'map Context'.
	 * @param mapContext String <b>Obligatoire</b>
	 */
	public void setMapContext(final String mapContext) {
		this.mapContext = mapContext;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
