package io.vertigo.chatbot.commons.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.Entity;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datastore.impl.entitystore.StoreVAccessor;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class ChatbotCustomConfig implements Entity {
	private static final long serialVersionUID = 1L;

	private Long cccId;
	private Boolean rating;
	private String ratingMessage;
	private String botEmailAddress;

	@io.vertigo.datamodel.structure.stereotype.Association(
			name = "AChatbotCustomConfigChatbot",
			fkFieldName = "botId",
			primaryDtDefinitionName = "DtChatbot",
			primaryIsNavigable = true,
			primaryRole = "Chatbot",
			primaryLabel = "Chatbot",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtChatbotCustomConfig",
			foreignIsNavigable = false,
			foreignRole = "ChatbotCustomConfig",
			foreignLabel = "ChatbotCustomConfig",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.chatbot.commons.domain.Chatbot> botIdAccessor = new StoreVAccessor<>(io.vertigo.chatbot.commons.domain.Chatbot.class, "Chatbot");

	/** {@inheritDoc} */
	@Override
	public UID<ChatbotCustomConfig> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Context value id'.
	 * @return Long cccId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Context value id")
	public Long getCccId() {
		return cccId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Context value id'.
	 * @param cccId Long <b>Obligatoire</b>
	 */
	public void setCccId(final Long cccId) {
		this.cccId = cccId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Rating'.
	 * @return Boolean rating <b>Obligatoire</b>
	 */
	@Field(smartType = "STyYesNo", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Rating")
	public Boolean getRating() {
		return rating;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Rating'.
	 * @param rating Boolean <b>Obligatoire</b>
	 */
	public void setRating(final Boolean rating) {
		this.rating = rating;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Rating message'.
	 * @return String ratingMessage
	 */
	@Field(smartType = "STyLabel", label = "Rating message")
	public String getRatingMessage() {
		return ratingMessage;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Rating message'.
	 * @param ratingMessage String
	 */
	public void setRatingMessage(final String ratingMessage) {
		this.ratingMessage = ratingMessage;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Bot email address'.
	 * @return String botEmailAddress
	 */
	@Field(smartType = "STyLabel", label = "Bot email address")
	public String getBotEmailAddress() {
		return botEmailAddress;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Bot email address'.
	 * @param botEmailAddress String
	 */
	public void setBotEmailAddress(final String botEmailAddress) {
		this.botEmailAddress = botEmailAddress;
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Chatbot'.
	 * @return Long botId <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.structure.stereotype.ForeignKey(smartType = "STyId", label = "Chatbot", fkDefinition = "DtChatbot" )
	public Long getBotId() {
		return (Long) botIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Chatbot'.
	 * @param botId Long <b>Obligatoire</b>
	 */
	public void setBotId(final Long botId) {
		botIdAccessor.setId(botId);
	}

 	/**
	 * Association : Chatbot.
	 * @return l'accesseur vers la propriété 'Chatbot'
	 */
	public StoreVAccessor<io.vertigo.chatbot.commons.domain.Chatbot> chatbot() {
		return botIdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
