package io.vertigo.chatbot.commons.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DocumentaryResourceExport implements DtObject {
	private static final long serialVersionUID = 1L;

	private String title;
	private String dreTypeCd;
	private String text;
	private String url;
	private String fileData;
	private String fileName;
	private String fileMimeType;
	private Long fileLength;
	private String fileUrn;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Title'.
	 * @return String title <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Title")
	public String getTitle() {
		return title;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Title'.
	 * @param title String <b>Obligatoire</b>
	 */
	public void setTitle(final String title) {
		this.title = title;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Resource Type'.
	 * @return String dreTypeCd <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Resource Type")
	public String getDreTypeCd() {
		return dreTypeCd;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Resource Type'.
	 * @param dreTypeCd String <b>Obligatoire</b>
	 */
	public void setDreTypeCd(final String dreTypeCd) {
		this.dreTypeCd = dreTypeCd;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Text'.
	 * @return String text
	 */
	@Field(smartType = "STyText", label = "Text")
	public String getText() {
		return text;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Text'.
	 * @param text String
	 */
	public void setText(final String text) {
		this.text = text;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Url'.
	 * @return String url
	 */
	@Field(smartType = "STyText", label = "Url")
	public String getUrl() {
		return url;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Url'.
	 * @param url String
	 */
	public void setUrl(final String url) {
		this.url = url;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'File data'.
	 * @return String fileData
	 */
	@Field(smartType = "STyText", label = "File data")
	public String getFileData() {
		return fileData;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'File data'.
	 * @param fileData String
	 */
	public void setFileData(final String fileData) {
		this.fileData = fileData;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'File name'.
	 * @return String fileName
	 */
	@Field(smartType = "STyLabel", label = "File name")
	public String getFileName() {
		return fileName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'File name'.
	 * @param fileName String
	 */
	public void setFileName(final String fileName) {
		this.fileName = fileName;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'File mime type'.
	 * @return String fileMimeType
	 */
	@Field(smartType = "STyLabel", label = "File mime type")
	public String getFileMimeType() {
		return fileMimeType;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'File mime type'.
	 * @param fileMimeType String
	 */
	public void setFileMimeType(final String fileMimeType) {
		this.fileMimeType = fileMimeType;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'File size'.
	 * @return Long fileLength
	 */
	@Field(smartType = "STySize", label = "File size")
	public Long getFileLength() {
		return fileLength;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'File size'.
	 * @param fileLength Long
	 */
	public void setFileLength(final Long fileLength) {
		this.fileLength = fileLength;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'File urn'.
	 * @return String fileUrn
	 */
	@Field(smartType = "STyText", label = "File urn")
	public String getFileUrn() {
		return fileUrn;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'File urn'.
	 * @param fileUrn String
	 */
	public void setFileUrn(final String fileUrn) {
		this.fileUrn = fileUrn;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
