package io.vertigo.chatbot.commons.domain;

import io.vertigo.dynamo.domain.model.Entity;
import io.vertigo.dynamo.domain.model.UID;
import io.vertigo.dynamo.domain.model.VAccessor;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class Training implements Entity {
	private static final long serialVersionUID = 1L;

	private Long traId;
	private java.time.Instant startTime;
	private java.time.Instant endTime;
	private Long versionNumber;
	private String tag;
	private Boolean valid;

	@io.vertigo.dynamo.domain.stereotype.Association(
			name = "ATrainingChatbot",
			fkFieldName = "botId",
			primaryDtDefinitionName = "DtChatbot",
			primaryIsNavigable = true,
			primaryRole = "Chatbot",
			primaryLabel = "Chatbot",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtTraining",
			foreignIsNavigable = false,
			foreignRole = "Training",
			foreignLabel = "Training",
			foreignMultiplicity = "0..*")
	private final VAccessor<io.vertigo.chatbot.commons.domain.Chatbot> botIdAccessor = new VAccessor<>(io.vertigo.chatbot.commons.domain.Chatbot.class, "Chatbot");

	/** {@inheritDoc} */
	@Override
	public UID<Training> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'ID'.
	 * @return Long traId <b>Obligatoire</b>
	 */
	@Field(domain = "DoId", type = "ID", required = true, label = "ID")
	public Long getTraId() {
		return traId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'ID'.
	 * @param traId Long <b>Obligatoire</b>
	 */
	public void setTraId(final Long traId) {
		this.traId = traId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Start time'.
	 * @return Instant startTime <b>Obligatoire</b>
	 */
	@Field(domain = "DoInstant", required = true, label = "Start time")
	public java.time.Instant getStartTime() {
		return startTime;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Start time'.
	 * @param startTime Instant <b>Obligatoire</b>
	 */
	public void setStartTime(final java.time.Instant startTime) {
		this.startTime = startTime;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'End time'.
	 * @return Instant endTime
	 */
	@Field(domain = "DoInstant", label = "End time")
	public java.time.Instant getEndTime() {
		return endTime;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'End time'.
	 * @param endTime Instant
	 */
	public void setEndTime(final java.time.Instant endTime) {
		this.endTime = endTime;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Version'.
	 * @return Long versionNumber <b>Obligatoire</b>
	 */
	@Field(domain = "DoNumber", required = true, label = "Version")
	public Long getVersionNumber() {
		return versionNumber;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Version'.
	 * @param versionNumber Long <b>Obligatoire</b>
	 */
	public void setVersionNumber(final Long versionNumber) {
		this.versionNumber = versionNumber;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Tag'.
	 * @return String tag
	 */
	@Field(domain = "DoLabel", label = "Tag")
	public String getTag() {
		return tag;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Tag'.
	 * @param tag String
	 */
	public void setTag(final String tag) {
		this.tag = tag;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Valide'.
	 * @return Boolean valid <b>Obligatoire</b>
	 */
	@Field(domain = "DoYesNo", required = true, label = "Valide")
	public Boolean getValid() {
		return valid;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Valide'.
	 * @param valid Boolean <b>Obligatoire</b>
	 */
	public void setValid(final Boolean valid) {
		this.valid = valid;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Chatbot'.
	 * @return Long botId <b>Obligatoire</b>
	 */
	@Field(domain = "DoId", type = "FOREIGN_KEY", required = true, label = "Chatbot")
	public Long getBotId() {
		return (Long) botIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Chatbot'.
	 * @param botId Long <b>Obligatoire</b>
	 */
	public void setBotId(final Long botId) {
		botIdAccessor.setId(botId);
	}

 	/**
	 * Association : Chatbot.
	 * @return l'accesseur vers la propriété 'Chatbot'
	 */
	public VAccessor<io.vertigo.chatbot.commons.domain.Chatbot> chatbot() {
		return botIdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
