package io.vertigo.chatbot.commons.domain.questionanswer;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class QuestionAnswerIhm implements DataObject {
	private static final long serialVersionUID = 1L;

	private Long qaId;
	private String question;
	private String answer;
	private Boolean isEnabled;
	private Long catId;
	private String catLabel;
	private String code;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Question-Answer id'.
	 * @return Long qaId
	 */
	@Field(smartType = "STyId", label = "Question-Answer id")
	public Long getQaId() {
		return qaId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Question-Answer id'.
	 * @param qaId Long
	 */
	public void setQaId(final Long qaId) {
		this.qaId = qaId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Question'.
	 * @return String question <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Question")
	public String getQuestion() {
		return question;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Question'.
	 * @param question String <b>Obligatoire</b>
	 */
	public void setQuestion(final String question) {
		this.question = question;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Answer'.
	 * @return String answer <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Answer")
	public String getAnswer() {
		return answer;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Answer'.
	 * @param answer String <b>Obligatoire</b>
	 */
	public void setAnswer(final String answer) {
		this.answer = answer;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Enabled'.
	 * @return Boolean isEnabled <b>Obligatoire</b>
	 */
	@Field(smartType = "STyYesNo", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Enabled")
	public Boolean getIsEnabled() {
		return isEnabled;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Enabled'.
	 * @param isEnabled Boolean <b>Obligatoire</b>
	 */
	public void setIsEnabled(final Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Category id'.
	 * @return Long catId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Category id")
	public Long getCatId() {
		return catId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Category id'.
	 * @param catId Long <b>Obligatoire</b>
	 */
	public void setCatId(final Long catId) {
		this.catId = catId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Category label'.
	 * @return String catLabel <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Category label")
	public String getCatLabel() {
		return catLabel;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Category label'.
	 * @param catLabel String <b>Obligatoire</b>
	 */
	public void setCatLabel(final String catLabel) {
		this.catLabel = catLabel;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Code'.
	 * @return String code <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Code")
	public String getCode() {
		return code;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Code'.
	 * @param code String <b>Obligatoire</b>
	 */
	public void setCode(final String code) {
		this.code = code;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
