package io.vertigo.chatbot.commons.domain.questionanswer;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class QuestionAnswerContextIhm implements DtObject {
	private static final long serialVersionUID = 1L;

	private Long qacId;
	private Long qaId;
	private Long cvaId;
	private Long cpvId;
	private String cvaLabel;
	private String cpvValue;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'ID'.
	 * @return Long qacId
	 */
	@Field(smartType = "STyId", label = "ID")
	public Long getQacId() {
		return qacId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'ID'.
	 * @param qacId Long
	 */
	public void setQacId(final Long qacId) {
		this.qacId = qacId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Question answer id'.
	 * @return Long qaId
	 */
	@Field(smartType = "STyId", label = "Question answer id")
	public Long getQaId() {
		return qaId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Question answer id'.
	 * @param qaId Long
	 */
	public void setQaId(final Long qaId) {
		this.qaId = qaId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Context value id'.
	 * @return Long cvaId
	 */
	@Field(smartType = "STyId", label = "Context value id")
	public Long getCvaId() {
		return cvaId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Context value id'.
	 * @param cvaId Long
	 */
	public void setCvaId(final Long cvaId) {
		this.cvaId = cvaId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Context possible value id'.
	 * @return Long cpvId
	 */
	@Field(smartType = "STyId", label = "Context possible value id")
	public Long getCpvId() {
		return cpvId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Context possible value id'.
	 * @param cpvId Long
	 */
	public void setCpvId(final Long cpvId) {
		this.cpvId = cpvId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Context'.
	 * @return String cvaLabel
	 */
	@Field(smartType = "STyLabel", label = "Context")
	public String getCvaLabel() {
		return cvaLabel;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Context'.
	 * @param cvaLabel String
	 */
	public void setCvaLabel(final String cvaLabel) {
		this.cvaLabel = cvaLabel;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Value'.
	 * @return String cpvValue
	 */
	@Field(smartType = "STyLabel", label = "Value")
	public String getCpvValue() {
		return cpvValue;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Value'.
	 * @param cpvValue String
	 */
	public void setCpvValue(final String cpvValue) {
		this.cpvValue = cpvValue;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
