package io.vertigo.chatbot.domain;

import java.util.Arrays;
import java.util.Iterator;

import io.vertigo.dynamo.domain.metamodel.DtFieldName;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DtDefinitions implements Iterable<Class<?>> {

	/**
	 * Enumération des DtDefinitions.
	 */
	public enum Definitions {
		/** Objet de données Intent. */
		Intent(io.vertigo.chatbot.designer.domain.Intent.class),
		/** Objet de données IntentText. */
		IntentText(io.vertigo.chatbot.designer.domain.IntentText.class)		;

		private final Class<?> clazz;

		private Definitions(final Class<?> clazz) {
			this.clazz = clazz;
		}

		/** 
		 * Classe associée.
		 * @return Class d'implémentation de l'objet 
		 */
		public Class<?> getDtClass() {
			return clazz;
		}
	}

	/**
	 * Enumération des champs de Intent.
	 */
	public enum IntentFields implements DtFieldName<io.vertigo.chatbot.designer.domain.Intent> {
		/** Propriété 'ID'. */
		intId,
		/** Propriété 'Titre'. */
		title	}

	/**
	 * Enumération des champs de IntentText.
	 */
	public enum IntentTextFields implements DtFieldName<io.vertigo.chatbot.designer.domain.IntentText> {
		/** Propriété 'ID'. */
		ittId,
		/** Propriété 'Text'. */
		text,
		/** Propriété 'Intent'. */
		intId	}

	/** {@inheritDoc} */
	@Override
	public Iterator<Class<?>> iterator() {
		return new Iterator<Class<?>>() {
			private Iterator<Definitions> it = Arrays.asList(Definitions.values()).iterator();

			/** {@inheritDoc} */
			@Override
			public boolean hasNext() {
				return it.hasNext();
			}

			/** {@inheritDoc} */
			@Override
			public Class<?> next() {
				return it.next().getDtClass();
			}
		};
	}
}
