ALTER TABLE CONTEXT_ENVIRONMENT_VALUE drop column VALUE;
ALTER TABLE CONTEXT_ENVIRONMENT_VALUE add column CPV_ID NUMERIC;
comment on column CONTEXT_ENVIRONMENT_VALUE.CPV_ID is 'ContextPossibleValue';

alter table CONTEXT_ENVIRONMENT_VALUE
    add constraint FK_A_CONTEXT_ENVIRONMENT_VALUE_CONTEXT_POSSIBLE_VALUE foreign key (CPV_ID)
        references CONTEXT_POSSIBLE_VALUE (CPV_ID);

create index A_CONTEXT_ENVIRONMENT_VALUE_CONTEXT_POSSIBLE_VALUE_FK on CONTEXT_ENVIRONMENT_VALUE (CPV_ID asc);
