package io.vertigo.chatbot.designer.builder.documentaryResourceContext;

import javax.inject.Inject;

import io.vertigo.core.node.Node;
import io.vertigo.core.lang.Assertion;
import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.task.TaskManager;
import io.vertigo.datamodel.task.definitions.TaskDefinition;
import io.vertigo.datamodel.task.model.Task;
import io.vertigo.datamodel.task.model.TaskBuilder;
import io.vertigo.datastore.impl.dao.StoreServices;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
 @Generated
public final class DocumentaryResourceContextPAO implements StoreServices {
	private final TaskManager taskManager;

	/**
	 * Constructeur.
	 * @param taskManager Manager des Task
	 */
	@Inject
	public DocumentaryResourceContextPAO(final TaskManager taskManager) {
		Assertion.check().isNotNull(taskManager);
		//-----
		this.taskManager = taskManager;
	}

	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Node.getNode().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TkGetAllDocumentaryResourceContextIhmByDreId.
	 * @param dreId Long
	 * @param locale String
	 * @return DtList de DocumentaryResourceContextIhm documentaryResourceContexts
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkGetAllDocumentaryResourceContextIhmByDreId",
			request = """
			SELECT 	drc.drc_id,
			        drc.dre_id,
					cva.cva_id,
					cpv.cpv_id,
					cva.label as cva_label,
					CASE #locale#
						WHEN 'fr_FR' THEN tyop.label_fr || ' : ' || cpv.value
						ELSE tyop.label || ' : ' || cpv.value
					END as cpv_value
			from documentary_resource_context drc
			join context_value cva on (cva.cva_id = drc.cva_id)
			left join context_possible_value cpv on (cpv.cpv_id = drc.cpv_id)
			left join type_operator tyop on (tyop.tyop_cd = cpv.tyop_cd)
			where drc.dre_id = #dreId#
			order by cva.label""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyDtDocumentaryResourceContextIhm", name = "documentaryResourceContexts")
	public io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.designer.domain.DocumentaryResourceContextIhm> getAllDocumentaryResourceContextIhmByDreId(@io.vertigo.datamodel.task.proxy.TaskInput(name = "dreId", smartType = "STyId") final Long dreId, @io.vertigo.datamodel.task.proxy.TaskInput(name = "locale", smartType = "STyCode") final String locale) {
		final Task task = createTaskBuilder("TkGetAllDocumentaryResourceContextIhmByDreId")
				.addValue("dreId", dreId)
				.addValue("locale", locale)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TkRemoveAllDocumentaryResourceContextByCvaId.
	 * @param cvaId Long
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkRemoveAllDocumentaryResourceContextByCvaId",
			request = """
			delete from documentary_resource_context
			where cva_id = #cvaId#""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineProc.class)
	public void removeAllDocumentaryResourceContextByCvaId(@io.vertigo.datamodel.task.proxy.TaskInput(name = "cvaId", smartType = "STyId") final Long cvaId) {
		final Task task = createTaskBuilder("TkRemoveAllDocumentaryResourceContextByCvaId")
				.addValue("cvaId", cvaId)
				.build();
		getTaskManager().execute(task);
	}

	/**
	 * Execute la tache TkRemoveAllDocumentaryResourceContextByDreId.
	 * @param dreId Long
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkRemoveAllDocumentaryResourceContextByDreId",
			request = """
			delete from documentary_resource_context
			where dre_id = #dreId#""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineProc.class)
	public void removeAllDocumentaryResourceContextByDreId(@io.vertigo.datamodel.task.proxy.TaskInput(name = "dreId", smartType = "STyId") final Long dreId) {
		final Task task = createTaskBuilder("TkRemoveAllDocumentaryResourceContextByDreId")
				.addValue("dreId", dreId)
				.build();
		getTaskManager().execute(task);
	}

	private TaskManager getTaskManager() {
		return taskManager;
	}
}
