package io.vertigo.chatbot.designer.builder.contextPossibleValue;

import javax.inject.Inject;

import io.vertigo.core.node.Node;
import io.vertigo.core.lang.Assertion;
import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.task.TaskManager;
import io.vertigo.datamodel.task.definitions.TaskDefinition;
import io.vertigo.datamodel.task.model.Task;
import io.vertigo.datamodel.task.model.TaskBuilder;
import io.vertigo.datastore.impl.dao.StoreServices;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
 @Generated
public final class ContextPossibleValuePAO implements StoreServices {
	private final TaskManager taskManager;

	/**
	 * Constructeur.
	 * @param taskManager Manager des Task
	 */
	@Inject
	public ContextPossibleValuePAO(final TaskManager taskManager) {
		Assertion.check().isNotNull(taskManager);
		//-----
		this.taskManager = taskManager;
	}

	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Node.getNode().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TkGetAllContextPossibleValueIhmByBotId.
	 * @param botId Long
	 * @param locale String
	 * @return DtList de ContextPossibleValueIhm contextPossibleValue
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkGetAllContextPossibleValueIhmByBotId",
			request = """
			SELECT 	cpv.cpv_id,
					CASE #locale#
						WHEN 'fr_FR' THEN tyop.label_fr || ' : ' || cpv.value
						ELSE tyop.label || ' : ' || cpv.value
					END as value,
					cpv.cva_id
			from context_possible_value cpv
			left join type_operator tyop on (tyop.tyop_cd = cpv.tyop_cd)
			where cpv.bot_id = #botId#
			order by cpv.value""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyDtContextPossibleValueIhm", name = "contextPossibleValue")
	public io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.designer.domain.ContextPossibleValueIhm> getAllContextPossibleValueIhmByBotId(@io.vertigo.datamodel.task.proxy.TaskInput(name = "botId", smartType = "STyId") final Long botId, @io.vertigo.datamodel.task.proxy.TaskInput(name = "locale", smartType = "STyCode") final String locale) {
		final Task task = createTaskBuilder("TkGetAllContextPossibleValueIhmByBotId")
				.addValue("botId", botId)
				.addValue("locale", locale)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	private TaskManager getTaskManager() {
		return taskManager;
	}
}
