ALTER TABLE SYNONYM DROP CONSTRAINT FK_A_SYNONYM_MEANING_MEANING;
ALTER TABLE MEANING DROP CONSTRAINT PK_MEANING;

ALTER TABLE MEANING RENAME COLUMN MEA_ID TO DIC_ENT_ID;

ALTER TABLE MEANING RENAME TO DICTIONARY_ENTITY;

ALTER TABLE DICTIONARY_ENTITY ADD CONSTRAINT PK_DICTIONARY_ENTITY PRIMARY KEY (DIC_ENT_ID);

DROP SEQUENCE IF EXISTS SEQ_MEANING;
CREATE SEQUENCE SEQ_DICTIONARY_ENTITY start with 2000 cache 20;
SELECT SETVAL('SEQ_DICTIONARY_ENTITY', GREATEST(2000, MAX(DIC_ENT_ID))::BIGINT) FROM DICTIONARY_ENTITY;

ALTER TABLE SYNONYM RENAME COLUMN MEA_ID TO DIC_ENT_ID;

ALTER TABLE SYNONYM
	ADD CONSTRAINT FK_A_SYNONYM_DICTIONARY_ENTITY_DICTIONARY_ENTITY FOREIGN KEY (DIC_ENT_ID)
	REFERENCES DICTIONARY_ENTITY (DIC_ENT_ID);

CREATE index A_SYNONYM_DICTIONARY_ENTITY_DICTIONARY_ENTITY_FK ON SYNONYM (DIC_ENT_ID ASC);