package io.vertigo.chatbot.designer.builder;

import javax.inject.Inject;

import io.vertigo.core.node.Node;
import io.vertigo.core.lang.Assertion;
import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.task.TaskManager;
import io.vertigo.datamodel.task.definitions.TaskDefinition;
import io.vertigo.datamodel.task.model.Task;
import io.vertigo.datamodel.task.model.TaskBuilder;
import io.vertigo.datastore.impl.dao.StoreServices;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
 @Generated
public final class BuilderPAO implements StoreServices {
	private final TaskManager taskManager;

	/**
	 * Constructeur.
	 * @param taskManager Manager des Task
	 */
	@Inject
	public BuilderPAO(final TaskManager taskManager) {
		Assertion.check().isNotNull(taskManager);
		//-----
		this.taskManager = taskManager;
	}

	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Node.getNode().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TkGetAllReponseTypeIdsByBotId.
	 * @param botId Long
	 * @return List de Long filIds
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkGetAllReponseTypeIdsByBotId",
			request = "select rty.rty_id\n" + 
 " 			from response_type rty\n" + 
 " 			join small_talk smt on (smt.rty_id = rty.rty_id)\n" + 
 " 			where smt.bot_id = #botId#",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyId", name = "filIds")
	public java.util.List<Long> getAllReponseTypeIdsByBotId(@io.vertigo.datamodel.task.proxy.TaskInput(name = "botId", smartType = "STyId") final Long botId) {
		final Task task = createTaskBuilder("TkGetAllReponseTypeIdsByBotId")
				.addValue("botId", botId)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TkRemoveAllReponseTypeByRtyIds.
	 * @param rtyIds List de Long
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkRemoveAllReponseTypeByRtyIds",
			request = "delete from response_type rty\n" + 
 " 			where rty.rty_id in (#rtyIds.rownum#)",
			taskEngineClass = io.vertigo.basics.task.TaskEngineProc.class)
	public void removeAllReponseTypeByRtyIds(@io.vertigo.datamodel.task.proxy.TaskInput(name = "rtyIds", smartType = "STyId") final java.util.List<Long> rtyIds) {
		final Task task = createTaskBuilder("TkRemoveAllReponseTypeByRtyIds")
				.addValue("rtyIds", rtyIds)
				.build();
		getTaskManager().execute(task);
	}

	private TaskManager getTaskManager() {
		return taskManager;
	}
}
