package io.vertigo.chatbot.designer.dao;

import javax.inject.Inject;

import java.util.Optional;
import io.vertigo.core.lang.Generated;
import io.vertigo.core.node.Node;
import io.vertigo.datamodel.task.definitions.TaskDefinition;
import io.vertigo.datamodel.task.model.Task;
import io.vertigo.datamodel.task.model.TaskBuilder;
import io.vertigo.datastore.entitystore.EntityStoreManager;
import io.vertigo.datastore.impl.dao.DAO;
import io.vertigo.datastore.impl.dao.StoreServices;
import io.vertigo.datamodel.smarttype.SmartTypeManager;
import io.vertigo.datamodel.task.TaskManager;
import io.vertigo.chatbot.designer.domain.Meaning;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class MeaningDAO extends DAO<Meaning, java.lang.Long> implements StoreServices {

	/**
	 * Contructeur.
	 * @param entityStoreManager Manager de persistance
	 * @param taskManager Manager de Task
	 * @param smartTypeManager SmartTypeManager
	 */
	@Inject
	public MeaningDAO(final EntityStoreManager entityStoreManager, final TaskManager taskManager, final SmartTypeManager smartTypeManager) {
		super(Meaning.class, entityStoreManager, taskManager, smartTypeManager);
	}


	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Node.getNode().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TkGetMeaningBySynonymLabelAndBotId.
	 * @param botId Long
	 * @param label String
	 * @return Option de Meaning meaning
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkGetMeaningBySynonymLabelAndBotId",
			request = "SELECT 	mea.*" + 
 "				from meaning mea " + 
 "				join synonym syn on syn.mea_id = mea.mea_id			" + 
 "				where mea.bot_id = #botId#			" + 
 "				and syn.label = #label#" + 
 "				LIMIT 1",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyDtMeaning")
	public Optional<io.vertigo.chatbot.designer.domain.Meaning> getMeaningBySynonymLabelAndBotId(@io.vertigo.datamodel.task.proxy.TaskInput(name = "botId", smartType = "STyId") final Long botId, @io.vertigo.datamodel.task.proxy.TaskInput(name = "label", smartType = "STyLabel") final String label) {
		final Task task = createTaskBuilder("TkGetMeaningBySynonymLabelAndBotId")
				.addValue("botId", botId)
				.addValue("label", label)
				.build();
		return Optional.ofNullable((io.vertigo.chatbot.designer.domain.Meaning) getTaskManager()
				.execute(task)
				.getResult());
	}

}
