package io.vertigo.chatbot.designer.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class ContextPossibleValueIhm implements DataObject {
	private static final long serialVersionUID = 1L;

	private Long cpvId;
	private String value;
	private Long cvaId;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Context possible value id'.
	 * @return Long cpvId
	 */
	@Field(smartType = "STyId", label = "Context possible value id")
	public Long getCpvId() {
		return cpvId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Context possible value id'.
	 * @param cpvId Long
	 */
	public void setCpvId(final Long cpvId) {
		this.cpvId = cpvId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Value'.
	 * @return String value
	 */
	@Field(smartType = "STyLabel", label = "Value")
	public String getValue() {
		return value;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Value'.
	 * @param value String
	 */
	public void setValue(final String value) {
		this.value = value;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Context value id'.
	 * @return Long cvaId
	 */
	@Field(smartType = "STyId", label = "Context value id")
	public Long getCvaId() {
		return cvaId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Context value id'.
	 * @param cvaId Long
	 */
	public void setCvaId(final Long cvaId) {
		this.cvaId = cvaId;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
