package io.vertigo.chatbot.designer.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.Entity;
import io.vertigo.datastore.impl.entitystore.EnumStoreVAccessor;
import io.vertigo.datamodel.data.model.UID;
import io.vertigo.datastore.impl.entitystore.StoreVAccessor;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DocumentaryResource implements Entity {
	private static final long serialVersionUID = 1L;

	private Long dreId;
	private String title;
	private String description;
	private String url;

	@io.vertigo.datamodel.data.stereotype.Association(
			name = "ADocumentaryResourceAttachmentFileInfo",
			fkFieldName = "attId",
			primaryDtDefinitionName = "DtAttachment",
			primaryIsNavigable = true,
			primaryRole = "Attachment",
			primaryLabel = "Attachment id",
			primaryMultiplicity = "0..1",
			foreignDtDefinitionName = "DtDocumentaryResource",
			foreignIsNavigable = false,
			foreignRole = "DocumentaryResource",
			foreignLabel = "DocumentaryResource",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.chatbot.commons.domain.Attachment> attIdAccessor = new StoreVAccessor<>(io.vertigo.chatbot.commons.domain.Attachment.class, "Attachment");

	@io.vertigo.datamodel.data.stereotype.Association(
			name = "ADocumentaryResourceDocumentaryResourceType",
			fkFieldName = "dreTypeCd",
			primaryDtDefinitionName = "DtDocumentaryResourceType",
			primaryIsNavigable = true,
			primaryRole = "DocumentaryResourceType",
			primaryLabel = "Documentary resource type",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtDocumentaryResource",
			foreignIsNavigable = false,
			foreignRole = "DocumentaryResource",
			foreignLabel = "DocumentaryResource",
			foreignMultiplicity = "0..*")
	private final EnumStoreVAccessor<io.vertigo.chatbot.designer.domain.DocumentaryResourceType, io.vertigo.chatbot.designer.domain.DocumentaryResourceTypeEnum> dreTypeCdAccessor = new EnumStoreVAccessor<>(io.vertigo.chatbot.designer.domain.DocumentaryResourceType.class, "DocumentaryResourceType", io.vertigo.chatbot.designer.domain.DocumentaryResourceTypeEnum.class);

	@io.vertigo.datamodel.data.stereotype.Association(
			name = "ADocumentaryResourceChatbot",
			fkFieldName = "botId",
			primaryDtDefinitionName = "DtChatbot",
			primaryIsNavigable = true,
			primaryRole = "Chatbot",
			primaryLabel = "Chatbot",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtDocumentaryResource",
			foreignIsNavigable = false,
			foreignRole = "DocumentaryResource",
			foreignLabel = "DocumentaryResource",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.chatbot.commons.domain.Chatbot> botIdAccessor = new StoreVAccessor<>(io.vertigo.chatbot.commons.domain.Chatbot.class, "Chatbot");

	/** {@inheritDoc} */
	@Override
	public UID<DocumentaryResource> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'ID'.
	 * @return Long dreId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "ID")
	public Long getDreId() {
		return dreId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'ID'.
	 * @param dreId Long <b>Obligatoire</b>
	 */
	public void setDreId(final Long dreId) {
		this.dreId = dreId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Title'.
	 * @return String title <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Title")
	public String getTitle() {
		return title;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Title'.
	 * @param title String <b>Obligatoire</b>
	 */
	public void setTitle(final String title) {
		this.title = title;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Description'.
	 * @return String description
	 */
	@Field(smartType = "STyText", label = "Description")
	public String getDescription() {
		return description;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Description'.
	 * @param description String
	 */
	public void setDescription(final String description) {
		this.description = description;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Url'.
	 * @return String url
	 */
	@Field(smartType = "STyText", label = "Url")
	public String getUrl() {
		return url;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Url'.
	 * @param url String
	 */
	public void setUrl(final String url) {
		this.url = url;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Attachment id'.
	 * @return Long attId
	 */
	@io.vertigo.datamodel.data.stereotype.ForeignKey(smartType = "STyId", label = "Attachment id", fkDefinition = "DtAttachment" )
	public Long getAttId() {
		return (Long) attIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Attachment id'.
	 * @param attId Long
	 */
	public void setAttId(final Long attId) {
		attIdAccessor.setId(attId);
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Documentary resource type'.
	 * @return String dreTypeCd <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.data.stereotype.ForeignKey(smartType = "STyCode", label = "Documentary resource type", fkDefinition = "DtDocumentaryResourceType", cardinality = io.vertigo.core.lang.Cardinality.ONE )
	public String getDreTypeCd() {
		return (String) dreTypeCdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Documentary resource type'.
	 * @param dreTypeCd String <b>Obligatoire</b>
	 */
	public void setDreTypeCd(final String dreTypeCd) {
		dreTypeCdAccessor.setId(dreTypeCd);
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Chatbot'.
	 * @return Long botId <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.data.stereotype.ForeignKey(smartType = "STyId", label = "Chatbot", fkDefinition = "DtChatbot", cardinality = io.vertigo.core.lang.Cardinality.ONE )
	public Long getBotId() {
		return (Long) botIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Chatbot'.
	 * @param botId Long <b>Obligatoire</b>
	 */
	public void setBotId(final Long botId) {
		botIdAccessor.setId(botId);
	}

 	/**
	 * Association : Attachment id.
	 * @return l'accesseur vers la propriété 'Attachment id'
	 */
	public StoreVAccessor<io.vertigo.chatbot.commons.domain.Attachment> attachment() {
		return attIdAccessor;
	}

 	/**
	 * Association : Chatbot.
	 * @return l'accesseur vers la propriété 'Chatbot'
	 */
	public StoreVAccessor<io.vertigo.chatbot.commons.domain.Chatbot> chatbot() {
		return botIdAccessor;
	}

 	/**
	 * Association : Documentary resource type.
	 * @return l'accesseur vers la propriété 'Documentary resource type'
	 */
	public EnumStoreVAccessor<io.vertigo.chatbot.designer.domain.DocumentaryResourceType, io.vertigo.chatbot.designer.domain.DocumentaryResourceTypeEnum> documentaryResourceType() {
		return dreTypeCdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
