package io.vertigo.chatbot.designer.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.Entity;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datastore.impl.entitystore.StoreVAccessor;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DocumentaryResourceUrl implements Entity {
	private static final long serialVersionUID = 1L;

	private Long urlId;
	private String url;

	@io.vertigo.datamodel.structure.stereotype.Association(
			name = "ADocumentaryResourceUrlDocumentaryResource",
			fkFieldName = "dreId",
			primaryDtDefinitionName = "DtDocumentaryResource",
			primaryIsNavigable = true,
			primaryRole = "DocumentaryResource",
			primaryLabel = "Documentary resource id",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtDocumentaryResourceUrl",
			foreignIsNavigable = false,
			foreignRole = "DocumentaryResourceUrl",
			foreignLabel = "DocumentaryResourceUrl",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.chatbot.designer.domain.DocumentaryResource> dreIdAccessor = new StoreVAccessor<>(io.vertigo.chatbot.designer.domain.DocumentaryResource.class, "DocumentaryResource");

	/** {@inheritDoc} */
	@Override
	public UID<DocumentaryResourceUrl> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'ID'.
	 * @return Long urlId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "ID")
	public Long getUrlId() {
		return urlId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'ID'.
	 * @param urlId Long <b>Obligatoire</b>
	 */
	public void setUrlId(final Long urlId) {
		this.urlId = urlId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'url'.
	 * @return String url <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "url")
	public String getUrl() {
		return url;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'url'.
	 * @param url String <b>Obligatoire</b>
	 */
	public void setUrl(final String url) {
		this.url = url;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Documentary resource id'.
	 * @return Long dreId <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.structure.stereotype.ForeignKey(smartType = "STyId", label = "Documentary resource id", fkDefinition = "DtDocumentaryResource", cardinality = io.vertigo.core.lang.Cardinality.ONE )
	public Long getDreId() {
		return (Long) dreIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Documentary resource id'.
	 * @param dreId Long <b>Obligatoire</b>
	 */
	public void setDreId(final Long dreId) {
		dreIdAccessor.setId(dreId);
	}

 	/**
	 * Association : Documentary resource id.
	 * @return l'accesseur vers la propriété 'Documentary resource id'
	 */
	public StoreVAccessor<io.vertigo.chatbot.designer.domain.DocumentaryResource> documentaryResource() {
		return dreIdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
