################################################################################");
# Attention ce fichier est généré automatiquement !");
# Resources du module io.vertigo.chatbot.designer.domain;
################################################################################");

fldContextEnvironment$cenvId = Context environment id
fldContextEnvironment$label = Label
fldContextEnvironment$botId = Chatbot

################################################################################");

fldContextEnvironmentIhm$cenvId = Context environment id
fldContextEnvironmentIhm$label = Label
fldContextEnvironmentIhm$contextEnvironmentValues = Context environment values

################################################################################");

fldContextEnvironmentValue$cenvalId = Context environment value id
fldContextEnvironmentValue$cvaId = Context
fldContextEnvironmentValue$cpvId = ContextPossibleValue
fldContextEnvironmentValue$cenvId = Environment

################################################################################");

fldContextEnvironmentValueIhm$cenvalId = Context environment value id
fldContextEnvironmentValueIhm$value = Value
fldContextEnvironmentValueIhm$displayValue = Value with operator
fldContextEnvironmentValueIhm$cpvId = Context possible value id
fldContextEnvironmentValueIhm$cvaId = Context value id
fldContextEnvironmentValueIhm$label = Context value label

################################################################################");

fldContextPossibleValueIhm$cpvId = Context possible value id
fldContextPossibleValueIhm$value = Value
fldContextPossibleValueIhm$cvaId = Context value id

################################################################################");

fldDictionaryEntity$dicEntId = Dictionary entity id
fldDictionaryEntity$label = Label
fldDictionaryEntity$botId = Chatbot

################################################################################");

fldDictionaryEntityWrapper$dicEntId = Dictionary Entity id
fldDictionaryEntityWrapper$dictionaryEntityLabel = Dictionary Entity Label
fldDictionaryEntityWrapper$synonymsList = Synonyms list

################################################################################");

fldDocumentaryResource$dreId = ID
fldDocumentaryResource$title = Title
fldDocumentaryResource$description = Description
fldDocumentaryResource$url = Url
fldDocumentaryResource$attId = Attachment id
fldDocumentaryResource$dreTypeCd = Documentary resource type
fldDocumentaryResource$botId = Chatbot

################################################################################");

fldDocumentaryResourceContext$drcId = ID
fldDocumentaryResourceContext$dreId = Documentary resource id
fldDocumentaryResourceContext$cvaId = Context value id
fldDocumentaryResourceContext$cpvId = Context possible value id

################################################################################");

fldDocumentaryResourceContextIhm$drcId = ID
fldDocumentaryResourceContextIhm$dreId = Documentary resource id
fldDocumentaryResourceContextIhm$cvaId = Context value id
fldDocumentaryResourceContextIhm$cpvId = Context possible value id
fldDocumentaryResourceContextIhm$cvaLabel = Context
fldDocumentaryResourceContextIhm$cpvValue = Value

################################################################################");

fldDocumentaryResourceType$dreTypeCd = Code
fldDocumentaryResourceType$label = Label
fldDocumentaryResourceType$labelFr = LabelFr

################################################################################");

fldGlobalVariable$glvId = ID
fldGlobalVariable$param1 = Param 1 value
fldGlobalVariable$param2 = Param 2 value
fldGlobalVariable$param3 = Param 3 value
fldGlobalVariable$param4 = Param 4 value
fldGlobalVariable$value = Global variable value
fldGlobalVariable$botId = Chatbot
fldGlobalVariable$gvtId = Global variable type

################################################################################");

fldGlobalVariableType$gvtId = ID
fldGlobalVariableType$label = Label
fldGlobalVariableType$botId = Chatbot

################################################################################");

fldHistory$histId = History id
fldHistory$date = Date
fldHistory$className = Class name
fldHistory$message = Label
fldHistory$userName = User
fldHistory$hacCd = Action
fldHistory$botId = Chatbot

################################################################################");

fldHistoryAction$hacCd = ID
fldHistoryAction$label = Title
fldHistoryAction$labelFr = TitleFr

################################################################################");

fldHistoryCriteria$fromDate = From
fldHistoryCriteria$toDate = To
fldHistoryCriteria$hacCd = Action
fldHistoryCriteria$text = Search

################################################################################");

fldSynonym$synId = Synonym id
fldSynonym$label = Label
fldSynonym$botId = Chatbot
fldSynonym$dicEntId = DictionaryEntity

################################################################################");

fldTupleSynonymIhm$word = Word
fldTupleSynonymIhm$synonymLabel = Synonym label

################################################################################");

