package io.vertigo.chatbot.designer.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.Entity;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datastore.impl.entitystore.StoreVAccessor;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class Synonym implements Entity {
	private static final long serialVersionUID = 1L;

	private Long synId;
	private String label;

	@io.vertigo.datamodel.structure.stereotype.Association(
			name = "ASynonymChatbot",
			fkFieldName = "botId",
			primaryDtDefinitionName = "DtChatbot",
			primaryIsNavigable = true,
			primaryRole = "Chatbot",
			primaryLabel = "Chatbot",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtSynonym",
			foreignIsNavigable = false,
			foreignRole = "Synonym",
			foreignLabel = "Synonym",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.chatbot.commons.domain.Chatbot> botIdAccessor = new StoreVAccessor<>(io.vertigo.chatbot.commons.domain.Chatbot.class, "Chatbot");

	@io.vertigo.datamodel.structure.stereotype.Association(
			name = "ASynonymDictionaryEntity",
			fkFieldName = "dicEntId",
			primaryDtDefinitionName = "DtDictionaryEntity",
			primaryIsNavigable = true,
			primaryRole = "DictionaryEntity",
			primaryLabel = "DictionaryEntity",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtSynonym",
			foreignIsNavigable = false,
			foreignRole = "Synonym",
			foreignLabel = "Synonym",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.chatbot.designer.domain.DictionaryEntity> dicEntIdAccessor = new StoreVAccessor<>(io.vertigo.chatbot.designer.domain.DictionaryEntity.class, "DictionaryEntity");

	/** {@inheritDoc} */
	@Override
	public UID<Synonym> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Synonym id'.
	 * @return Long synId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Synonym id")
	public Long getSynId() {
		return synId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Synonym id'.
	 * @param synId Long <b>Obligatoire</b>
	 */
	public void setSynId(final Long synId) {
		this.synId = synId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Label'.
	 * @return String label <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Label")
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Label'.
	 * @param label String <b>Obligatoire</b>
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Chatbot'.
	 * @return Long botId <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.structure.stereotype.ForeignKey(smartType = "STyId", label = "Chatbot", fkDefinition = "DtChatbot" )
	public Long getBotId() {
		return (Long) botIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Chatbot'.
	 * @param botId Long <b>Obligatoire</b>
	 */
	public void setBotId(final Long botId) {
		botIdAccessor.setId(botId);
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'DictionaryEntity'.
	 * @return Long dicEntId <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.structure.stereotype.ForeignKey(smartType = "STyId", label = "DictionaryEntity", fkDefinition = "DtDictionaryEntity" )
	public Long getDicEntId() {
		return (Long) dicEntIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'DictionaryEntity'.
	 * @param dicEntId Long <b>Obligatoire</b>
	 */
	public void setDicEntId(final Long dicEntId) {
		dicEntIdAccessor.setId(dicEntId);
	}

 	/**
	 * Association : Chatbot.
	 * @return l'accesseur vers la propriété 'Chatbot'
	 */
	public StoreVAccessor<io.vertigo.chatbot.commons.domain.Chatbot> chatbot() {
		return botIdAccessor;
	}

 	/**
	 * Association : DictionaryEntity.
	 * @return l'accesseur vers la propriété 'DictionaryEntity'
	 */
	public StoreVAccessor<io.vertigo.chatbot.designer.domain.DictionaryEntity> dictionaryEntity() {
		return dicEntIdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
