package io.vertigo.chatbot.designer.builder.questionAnswer;

import javax.inject.Inject;

import io.vertigo.core.node.Node;
import io.vertigo.core.lang.Assertion;
import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.task.TaskManager;
import io.vertigo.datamodel.task.definitions.TaskDefinition;
import io.vertigo.datamodel.task.model.Task;
import io.vertigo.datamodel.task.model.TaskBuilder;
import io.vertigo.datastore.impl.dao.StoreServices;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
 @Generated
public final class QuestionAnswerPAO implements StoreServices {
	private final TaskManager taskManager;

	/**
	 * Constructeur.
	 * @param taskManager Manager des Task
	 */
	@Inject
	public QuestionAnswerPAO(final TaskManager taskManager) {
		Assertion.check().isNotNull(taskManager);
		//-----
		this.taskManager = taskManager;
	}

	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Node.getNode().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TkGetAllQuestionAnswerIhmFromBot.
	 * @param botId Long
	 * @return DtList de QuestionAnswerIhm questionanswerIHM
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkGetAllQuestionAnswerIhmFromBot",
			request = """
			SELECT 	qa.qa_id,
					qa.question,
					qa.answer,
					qa.is_enabled,
					qa.code,
					qa.sequence,
					qac.qa_cat_id as cat_id,
					qac.label as cat_label
			from question_answer qa
			join question_answer_category qac on (qac.qa_cat_id = qa.qa_cat_id)
			where qa.bot_id = #botId#
			order by qac.sequence,
                    qa.sequence""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyDtQuestionAnswerIhm", name = "questionanswerIHM")
	public io.vertigo.datamodel.data.model.DtList<io.vertigo.chatbot.commons.domain.questionanswer.QuestionAnswerIhm> getAllQuestionAnswerIhmFromBot(@io.vertigo.datamodel.task.proxy.TaskInput(name = "botId", smartType = "STyId") final Long botId) {
		final Task task = createTaskBuilder("TkGetAllQuestionAnswerIhmFromBot")
				.addValue("botId", botId)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TkGetNextQueAnsCatSequence.
	 * @param botId Long
	 * @return Long nextQueAnsCatSequence
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkGetNextQueAnsCatSequence",
			request = """
			select coalesce(max(sequence) + 1, 1)
			from question_answer_category qac
			where qac.bot_id = #botId#""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyNumber", name = "nextQueAnsCatSequence")
	public Long getNextQueAnsCatSequence(@io.vertigo.datamodel.task.proxy.TaskInput(name = "botId", smartType = "STyId") final Long botId) {
		final Task task = createTaskBuilder("TkGetNextQueAnsCatSequence")
				.addValue("botId", botId)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TkGetNextQueAnsSequence.
	 * @param qaCatId Long
	 * @return Long nextQueAnsSequence
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkGetNextQueAnsSequence",
			request = """
			select coalesce(max(sequence) + 1, 1)
			from question_answer qa
			where qa.qa_cat_id = #qaCatId#""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyNumber", name = "nextQueAnsSequence")
	public Long getNextQueAnsSequence(@io.vertigo.datamodel.task.proxy.TaskInput(name = "qaCatId", smartType = "STyId") final Long qaCatId) {
		final Task task = createTaskBuilder("TkGetNextQueAnsSequence")
				.addValue("qaCatId", qaCatId)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TkGetQuestionAnswerIhmById.
	 * @param qaId Long
	 * @return QuestionAnswerIhm questionAnswerIHM
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkGetQuestionAnswerIhmById",
			request = """
			SELECT 	qa.qa_id,
                    qa.question,
                    qa.answer,
                    qa.is_enabled,
                    qa.code,
                    qa.sequence,
                    qac.qa_cat_id as cat_id,
                    qac.label as cat_label
			from question_answer qa
            join question_answer_category qac on (qac.qa_cat_id = qa.qa_cat_id)
			where qa.qa_id = #qaId#

			LIMIT 1""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyDtQuestionAnswerIhm", name = "questionAnswerIHM")
	public io.vertigo.chatbot.commons.domain.questionanswer.QuestionAnswerIhm getQuestionAnswerIhmById(@io.vertigo.datamodel.task.proxy.TaskInput(name = "qaId", smartType = "STyId") final Long qaId) {
		final Task task = createTaskBuilder("TkGetQuestionAnswerIhmById")
				.addValue("qaId", qaId)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TkReorderQueAnsAfterDelete.
	 * @param qaCatId Long
	 * @param deletedSequence Long
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkReorderQueAnsAfterDelete",
			request = """
			update question_answer
			set sequence = (sequence - 1)
			where qa_cat_id = #qaCatId# and sequence > #deletedSequence#""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineProc.class)
	public void reorderQueAnsAfterDelete(@io.vertigo.datamodel.task.proxy.TaskInput(name = "qaCatId", smartType = "STyId") final Long qaCatId, @io.vertigo.datamodel.task.proxy.TaskInput(name = "deletedSequence", smartType = "STyNumber") final Long deletedSequence) {
		final Task task = createTaskBuilder("TkReorderQueAnsAfterDelete")
				.addValue("qaCatId", qaCatId)
				.addValue("deletedSequence", deletedSequence)
				.build();
		getTaskManager().execute(task);
	}

	/**
	 * Execute la tache TkReorderQueAnsCatAfterDelete.
	 * @param botId Long
	 * @param deletedSequence Long
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkReorderQueAnsCatAfterDelete",
			request = """
			update question_answer_category
			set sequence = (sequence - 1)
			where bot_id = #botId# and sequence > #deletedSequence#""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineProc.class)
	public void reorderQueAnsCatAfterDelete(@io.vertigo.datamodel.task.proxy.TaskInput(name = "botId", smartType = "STyId") final Long botId, @io.vertigo.datamodel.task.proxy.TaskInput(name = "deletedSequence", smartType = "STyNumber") final Long deletedSequence) {
		final Task task = createTaskBuilder("TkReorderQueAnsCatAfterDelete")
				.addValue("botId", botId)
				.addValue("deletedSequence", deletedSequence)
				.build();
		getTaskManager().execute(task);
	}

	private TaskManager getTaskManager() {
		return taskManager;
	}
}
