package io.vertigo.chatbot.designer.builder.topicLabel;

import javax.inject.Inject;

import io.vertigo.core.node.Node;
import io.vertigo.core.lang.Assertion;
import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.task.TaskManager;
import io.vertigo.datamodel.task.definitions.TaskDefinition;
import io.vertigo.datamodel.task.model.Task;
import io.vertigo.datamodel.task.model.TaskBuilder;
import io.vertigo.datastore.impl.dao.StoreServices;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
 @Generated
public final class TopicLabelPAO implements StoreServices {
	private final TaskManager taskManager;

	/**
	 * Constructeur.
	 * @param taskManager Manager des Task
	 */
	@Inject
	public TopicLabelPAO(final TaskManager taskManager) {
		Assertion.check().isNotNull(taskManager);
		//-----
		this.taskManager = taskManager;
	}

	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Node.getNode().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TkRemoveFromNNTopicLabel.
	 * @param tpls List de Long
	 * @param topId Long
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkRemoveFromNNTopicLabel",
			request = "delete from topic_topic_label" + 
 "				where top_id = #topId# and label_id = #tpls.rownum#;",
			taskEngineClass = io.vertigo.basics.task.TaskEngineProc.class)
	public void removeFromNNTopicLabel(@io.vertigo.datamodel.task.proxy.TaskInput(name = "tpls", smartType = "STyId") final java.util.List<Long> tpls, @io.vertigo.datamodel.task.proxy.TaskInput(name = "topId", smartType = "STyId") final Long topId) {
		final Task task = createTaskBuilder("TkRemoveFromNNTopicLabel")
				.addValue("tpls", tpls)
				.addValue("topId", topId)
				.build();
		getTaskManager().execute(task);
	}

	/**
	 * Execute la tache TkUpdateNNTopicLabel.
	 * @param tpls List de Long
	 * @param topId Long
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkUpdateNNTopicLabel",
			request = "INSERT INTO topic_topic_label" + 
 "				(top_id, label_id)" + 
 "				VALUES(#topId#, #tpls.rownum#);",
			taskEngineClass = io.vertigo.basics.task.TaskEngineProcBatch.class)
	public void updateNNTopicLabel(@io.vertigo.datamodel.task.proxy.TaskInput(name = "tpls", smartType = "STyId") final java.util.List<Long> tpls, @io.vertigo.datamodel.task.proxy.TaskInput(name = "topId", smartType = "STyId") final Long topId) {
		final Task task = createTaskBuilder("TkUpdateNNTopicLabel")
				.addValue("tpls", tpls)
				.addValue("topId", topId)
				.build();
		getTaskManager().execute(task);
	}

	private TaskManager getTaskManager() {
		return taskManager;
	}
}
