package io.vertigo.chatbot.commons.domain.topic;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class SelectCategory implements DtObject {
	private static final long serialVersionUID = 1L;

	private java.util.List<Long> topCatId = new java.util.ArrayList<>();
	private String code;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Category id'.
	 * @return List de Long topCatId
	 */
	@Field(smartType = "STyId", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Category id")
	public java.util.List<Long> getTopCatId() {
		return topCatId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Category id'.
	 * @param topCatId List de Long
	 */
	public void setTopCatId(final java.util.List<Long> topCatId) {
		io.vertigo.core.lang.Assertion.check().isNotNull(topCatId);
		//---
		this.topCatId = topCatId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Code'.
	 * @return String code
	 */
	@Field(smartType = "STyCode", label = "Code")
	public String getCode() {
		return code;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Code'.
	 * @param code String
	 */
	public void setCode(final String code) {
		this.code = code;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
