package io.vertigo.chatbot.commons.domain.topic;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class TopicIhm implements DtObject {
	private static final long serialVersionUID = 1L;

	private Long topId;
	private String ttoCd;
	private String type;
	private String title;
	private Long smtId;
	private Long sinId;
	private String catLabel;
	private Boolean isEnabled;
	private String ktoCd;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Topic id'.
	 * @return Long topId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Topic id")
	public Long getTopId() {
		return topId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Topic id'.
	 * @param topId Long <b>Obligatoire</b>
	 */
	public void setTopId(final Long topId) {
		this.topId = topId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Code Type'.
	 * @return String ttoCd
	 */
	@Field(smartType = "STyCode", label = "Code Type")
	public String getTtoCd() {
		return ttoCd;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Code Type'.
	 * @param ttoCd String
	 */
	public void setTtoCd(final String ttoCd) {
		this.ttoCd = ttoCd;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Type'.
	 * @return String type
	 */
	@Field(smartType = "STyLabel", label = "Type")
	public String getType() {
		return type;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Type'.
	 * @param type String
	 */
	public void setType(final String type) {
		this.type = type;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Topic label'.
	 * @return String title
	 */
	@Field(smartType = "STyLabel", label = "Topic label")
	public String getTitle() {
		return title;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Topic label'.
	 * @param title String
	 */
	public void setTitle(final String title) {
		this.title = title;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'SmallTalk id'.
	 * @return Long smtId
	 */
	@Field(smartType = "STyId", label = "SmallTalk id")
	public Long getSmtId() {
		return smtId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'SmallTalk id'.
	 * @param smtId Long
	 */
	public void setSmtId(final Long smtId) {
		this.smtId = smtId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Script intention id'.
	 * @return Long sinId
	 */
	@Field(smartType = "STyId", label = "Script intention id")
	public Long getSinId() {
		return sinId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Script intention id'.
	 * @param sinId Long
	 */
	public void setSinId(final Long sinId) {
		this.sinId = sinId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Category'.
	 * @return String catLabel <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Category")
	public String getCatLabel() {
		return catLabel;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Category'.
	 * @param catLabel String <b>Obligatoire</b>
	 */
	public void setCatLabel(final String catLabel) {
		this.catLabel = catLabel;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Enabled'.
	 * @return Boolean isEnabled
	 */
	@Field(smartType = "STyYesNo", label = "Enabled")
	public Boolean getIsEnabled() {
		return isEnabled;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Enabled'.
	 * @param isEnabled Boolean
	 */
	public void setIsEnabled(final Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Code Kind'.
	 * @return String ktoCd
	 */
	@Field(smartType = "STyCode", label = "Code Kind")
	public String getKtoCd() {
		return ktoCd;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Code Kind'.
	 * @param ktoCd String
	 */
	public void setKtoCd(final String ktoCd) {
		this.ktoCd = ktoCd;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
