ALTER TABLE CHATBOT_CUSTOM_CONFIG DROP COLUMN RATING;
ALTER TABLE CHATBOT_CUSTOM_CONFIG DROP COLUMN RATING_MESSAGE;
ALTER TABLE CHATBOT_CUSTOM_CONFIG DROP COLUMN COMMENT;
ALTER TABLE CHATBOT_CUSTOM_CONFIG DROP COLUMN COMMENT_MESSAGE;