ALTER TABLE chatbot_custom_config ALTER COLUMN BACKGROUND_COLOR SET DEFAULT '#000091';
ALTER TABLE chatbot_custom_config ALTER COLUMN BOT_MESSAGE_BACKGROUND_COLOR SET DEFAULT '#ffffff';
ALTER TABLE chatbot_custom_config ALTER COLUMN BOT_MESSAGE_FONT_COLOR SET DEFAULT '#000000';
ALTER TABLE chatbot_custom_config ALTER COLUMN USER_MESSAGE_FONT_COLOR SET DEFAULT '#000000';
ALTER TABLE chatbot_custom_config ADD COLUMN FONT_COLOR VARCHAR(100) DEFAULT '#ffffff';
ALTER TABLE chatbot_custom_config ADD COLUMN USER_MESSAGE_BACKGROUND_COLOR VARCHAR(100) DEFAULT '#e0e0e0';