ALTER TABLE DOCUMENTARY_RESOURCE
    ADD COLUMN CVA_ID NUMERIC,
    ADD COLUMN CPV_ID NUMERIC;

comment on column DOCUMENTARY_RESOURCE.CVA_ID is
'Context value id';

comment on column DOCUMENTARY_RESOURCE.CPV_ID is
'Context possible value id';


ALTER TABLE QUESTION_ANSWER
    ADD COLUMN CVA_ID NUMERIC,
    ADD COLUMN CPV_ID NUMERIC;

comment on column QUESTION_ANSWER.CVA_ID is
'Context value id';

comment on column QUESTION_ANSWER.CPV_ID is
'Context possible value id';

alter table DOCUMENTARY_RESOURCE
    add constraint FK_A_DOCUMENTARY_RESOURCE_CONTEXT_POSSIBLE_VALUE_CONTEXT_POSSIBLE_VALUE foreign key (CPV_ID)
        references CONTEXT_POSSIBLE_VALUE (CPV_ID);

create index A_DOCUMENTARY_RESOURCE_CONTEXT_POSSIBLE_VALUE_CONTEXT_POSSIBLE_VALUE_FK on DOCUMENTARY_RESOURCE (CPV_ID asc);

alter table DOCUMENTARY_RESOURCE
    add constraint FK_A_DOCUMENTARY_RESOURCE_CONTEXT_VALUE_CONTEXT_VALUE foreign key (CVA_ID)
        references CONTEXT_VALUE (CVA_ID);

create index A_DOCUMENTARY_RESOURCE_CONTEXT_VALUE_CONTEXT_VALUE_FK on DOCUMENTARY_RESOURCE (CVA_ID asc);
