package io.vertigo.chatbot.designer.builder.topic.export;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class ResponseButtonExport implements DtObject {
	private static final long serialVersionUID = 1L;

	private Long topId;
	private Long topCode;
	private Long topCodeResponse;
	private String text;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Topic id'.
	 * @return Long topId
	 */
	@Field(smartType = "STyId", label = "Topic id")
	public Long getTopId() {
		return topId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Topic id'.
	 * @param topId Long
	 */
	public void setTopId(final Long topId) {
		this.topId = topId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Topic code'.
	 * @return Long topCode
	 */
	@Field(smartType = "STyId", label = "Topic code")
	public Long getTopCode() {
		return topCode;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Topic code'.
	 * @param topCode Long
	 */
	public void setTopCode(final Long topCode) {
		this.topCode = topCode;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Topic code response'.
	 * @return Long topCodeResponse
	 */
	@Field(smartType = "STyId", label = "Topic code response")
	public Long getTopCodeResponse() {
		return topCodeResponse;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Topic code response'.
	 * @param topCodeResponse Long
	 */
	public void setTopCodeResponse(final Long topCodeResponse) {
		this.topCodeResponse = topCodeResponse;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Button text'.
	 * @return String text
	 */
	@Field(smartType = "STyText", label = "Button text")
	public String getText() {
		return text;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Button text'.
	 * @param text String
	 */
	public void setText(final String text) {
		this.text = text;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
