package io.vertigo.chatbot.designer.builder.topic.export;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class UtterTextExport implements DtObject {
	private static final long serialVersionUID = 1L;

	private Long topId;
	private String utterTexts;
	private String responseType;
	private Boolean isEnd;
	private String ktoCd;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Topic id'.
	 * @return Long topId
	 */
	@Field(smartType = "STyId", label = "Topic id")
	public Long getTopId() {
		return topId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Topic id'.
	 * @param topId Long
	 */
	public void setTopId(final Long topId) {
		this.topId = topId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Utters'.
	 * @return String utterTexts
	 */
	@Field(smartType = "STyText", label = "Utters")
	public String getUtterTexts() {
		return utterTexts;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Utters'.
	 * @param utterTexts String
	 */
	public void setUtterTexts(final String utterTexts) {
		this.utterTexts = utterTexts;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Response type'.
	 * @return String responseType
	 */
	@Field(smartType = "STyText", label = "Response type")
	public String getResponseType() {
		return responseType;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Response type'.
	 * @param responseType String
	 */
	public void setResponseType(final String responseType) {
		this.responseType = responseType;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Is conversation over ?'.
	 * @return Boolean isEnd
	 */
	@Field(smartType = "STyYesNo", label = "Is conversation over ?")
	public Boolean getIsEnd() {
		return isEnd;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Is conversation over ?'.
	 * @param isEnd Boolean
	 */
	public void setIsEnd(final Boolean isEnd) {
		this.isEnd = isEnd;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Kind Topic Code'.
	 * @return String ktoCd
	 */
	@Field(smartType = "STyCode", label = "Kind Topic Code")
	public String getKtoCd() {
		return ktoCd;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Kind Topic Code'.
	 * @param ktoCd String
	 */
	public void setKtoCd(final String ktoCd) {
		this.ktoCd = ktoCd;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
